import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

type Category={id:string;code:string;name_th:string;name_en:string};
type Supplier={id:string;supplier_name:string};
type Expense={id:string;expense_date:string;description:string;amount:number;payment_method:string|null;reference_no:string|null;receipt_url:string|null;status:string;created_by:string;expense_categories?:{name_th?:string;code?:string}|null;suppliers?:{supplier_name?:string}|null};

const MAX_RECEIPT_BYTES=5*1024*1024;
const ALLOWED_RECEIPTS=['application/pdf','image/jpeg','image/png','image/webp'];

export function ExpensesPage(){
 const[categories,setCategories]=useState<Category[]>([]);const[suppliers,setSuppliers]=useState<Supplier[]>([]);const[rows,setRows]=useState<Expense[]>([]);const[category,setCategory]=useState('');const[supplier,setSupplier]=useState('');const[description,setDescription]=useState('');const[amount,setAmount]=useState('');const[payment,setPayment]=useState('');const[reference,setReference]=useState('');const[receipt,setReceipt]=useState<File|null>(null);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const[a,b,c]=await Promise.all([supabase.from('expense_categories').select('id,code,name_th,name_en').eq('is_active',true).order('code'),supabase.from('suppliers').select('id,supplier_name').eq('is_active',true).order('supplier_name'),supabase.from('expenses').select('id,expense_date,description,amount,payment_method,reference_no,receipt_url,status,created_by,expense_categories(name_th,code),suppliers(supplier_name)').order('expense_date',{ascending:false}).order('created_at',{ascending:false}).limit(100)]);if(a.error||b.error||c.error){setMsg(a.error?.message||b.error?.message||c.error?.message||'โหลดข้อมูลค่าใช้จ่ายไม่สำเร็จ');return}setCategories((a.data??[]) as Category[]);setSuppliers((b.data??[]) as Supplier[]);setRows((c.data??[]) as unknown as Expense[])},[]);
 useEffect(()=>{void load()},[load]);
 async function uploadReceipt(file:File){if(file.size>MAX_RECEIPT_BYTES)throw new Error('ไฟล์ใบเสร็จต้องไม่เกิน 5 MB');if(!ALLOWED_RECEIPTS.includes(file.type))throw new Error('รองรับเฉพาะ PDF, JPG, PNG และ WebP');const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('กรุณาเข้าสู่ระบบใหม่');const ext=(file.name.split('.').pop()||'bin').toLowerCase();const path=`${user.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const{error}=await supabase.storage.from('expense-receipts').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return path}
 async function submit(e:React.FormEvent){e.preventDefault();const n=Number(amount);setMsg('');if(!category||!description.trim()||!Number.isFinite(n)||n<=0){setMsg('กรุณาระบุหมวด รายละเอียด และจำนวนเงินมากกว่า 0');return}setBusy(true);let receiptPath:string|null=null;try{if(receipt)receiptPath=await uploadReceipt(receipt);const{error}=await supabase.rpc('record_expense',{p_expense_date:new Date().toISOString().slice(0,10),p_category_id:category,p_description:description.trim(),p_amount:n,p_payment_method:payment||null,p_supplier_id:supplier||null,p_reference_no:reference||null,p_notes:null,p_receipt_url:receiptPath});if(error)throw error;setDescription('');setAmount('');setPayment('');setReference('');setReceipt(null);setMsg('บันทึกค่าใช้จ่ายเรียบร้อยแล้ว');await load()}catch(error){if(receiptPath)await supabase.storage.from('expense-receipts').remove([receiptPath]);setMsg(error instanceof Error?error.message:'บันทึกค่าใช้จ่ายไม่สำเร็จ')}finally{setBusy(false)}}
 async function viewReceipt(path:string){const{data,error}=await supabase.storage.from('expense-receipts').createSignedUrl(path,60);if(error){setMsg(error.message);return}window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 async function voidExpense(id:string){const reason=window.prompt('เหตุผลในการยกเลิกรายการค่าใช้จ่าย');if(reason===null)return;const{error}=await supabase.rpc('void_expense',{p_expense_id:id,p_reason:reason});if(error){setMsg(error.message);return}setMsg('ยกเลิกรายการค่าใช้จ่ายแล้ว');await load()}
 return <><h1>ค่าใช้จ่าย</h1><p className="lead">บันทึกค่าใช้จ่ายดำเนินงานแยกจากการซื้อวัตถุดิบ หากเป็นวัตถุดิบหรือบรรจุภัณฑ์ที่ต้องเพิ่มสต็อก ควรบันทึกผ่านเมนูจัดซื้อ</p><div className="panel"><form className="crudform" onSubmit={e=>void submit(e)}><select value={category} onChange={e=>setCategory(e.target.value)} required><option value="">หมวดค่าใช้จ่าย</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name_th} ({c.code})</option>)}</select><select value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">ผู้ขาย (ถ้ามี)</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.supplier_name}</option>)}</select><input placeholder="รายละเอียด" value={description} onChange={e=>setDescription(e.target.value)} required/><input type="number" min="0.01" step="0.01" placeholder="จำนวนเงิน (บาท)" value={amount} onChange={e=>setAmount(e.target.value)} required/><input placeholder="ช่องทางชำระเงิน" value={payment} onChange={e=>setPayment(e.target.value)}/><input placeholder="เลขอ้างอิง" value={reference} onChange={e=>setReference(e.target.value)}/><label className="filepick">ใบเสร็จ (PDF/JPG/PNG/WebP ไม่เกิน 5 MB)<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>setReceipt(e.target.files?.[0]??null)}/></label><button disabled={busy}>{busy?'กำลังบันทึก...':'บันทึกค่าใช้จ่าย'}</button></form>{receipt&&<p className="muted">ไฟล์: {receipt.name}</p>}{msg&&<div className="warn">{msg}</div>}</div><div className="panel"><h2>ค่าใช้จ่ายล่าสุด</h2><div className="tablewrap"><table><thead><tr><th>วันที่</th><th>หมวด</th><th>รายละเอียด</th><th>ผู้ขาย</th><th>จำนวนเงิน</th><th>ชำระเงิน</th><th>ใบเสร็จ</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.expense_date}</td><td>{r.expense_categories?.name_th??r.expense_categories?.code??''}</td><td>{r.description}</td><td>{r.suppliers?.supplier_name??''}</td><td>฿{Number(r.amount).toFixed(2)}</td><td>{r.payment_method??''}</td><td>{r.receipt_url?<button className="smallbtn" onClick={()=>void viewReceipt(r.receipt_url!)}>เปิดใบเสร็จ</button>:'—'}</td><td>{r.status==='ACTIVE'?'ใช้งาน':'ยกเลิก'}</td><td>{r.status==='ACTIVE'&&<button className="smallbtn danger" onClick={()=>void voidExpense(r.id)}>ยกเลิก</button>}</td></tr>)}</tbody></table></div></div></>;
}
