import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

type Category={id:string;code:string;name_th:string;name_en:string};
type Supplier={id:string;supplier_name:string};
type Expense={id:string;expense_date:string;description:string;amount:number;payment_method:string|null;reference_no:string|null;status:string;created_by:string;expense_categories?:{name_th?:string;code?:string}|null;suppliers?:{supplier_name?:string}|null};

export function ExpensesPage(){
 const[categories,setCategories]=useState<Category[]>([]);const[suppliers,setSuppliers]=useState<Supplier[]>([]);const[rows,setRows]=useState<Expense[]>([]);const[category,setCategory]=useState('');const[supplier,setSupplier]=useState('');const[description,setDescription]=useState('');const[amount,setAmount]=useState('');const[payment,setPayment]=useState('');const[reference,setReference]=useState('');const[msg,setMsg]=useState('');
 const load=useCallback(async()=>{const[a,b,c]=await Promise.all([supabase.from('expense_categories').select('id,code,name_th,name_en').eq('is_active',true).order('code'),supabase.from('suppliers').select('id,supplier_name').eq('is_active',true).order('supplier_name'),supabase.from('expenses').select('id,expense_date,description,amount,payment_method,reference_no,status,created_by,expense_categories(name_th,code),suppliers(supplier_name)').order('expense_date',{ascending:false}).order('created_at',{ascending:false}).limit(100)]);if(a.error||b.error||c.error){setMsg(a.error?.message||b.error?.message||c.error?.message||'Unable to load expense data');return}setCategories((a.data??[]) as Category[]);setSuppliers((b.data??[]) as Supplier[]);setRows((c.data??[]) as unknown as Expense[])},[]);
 useEffect(()=>{void load()},[load]);
 async function submit(e:React.FormEvent){e.preventDefault();const n=Number(amount);setMsg('');if(!category||!description.trim()||!Number.isFinite(n)||n<=0){setMsg('Category, description and amount greater than zero are required.');return}const{error}=await supabase.rpc('record_expense',{p_expense_date:new Date().toISOString().slice(0,10),p_category_id:category,p_description:description.trim(),p_amount:n,p_payment_method:payment||null,p_supplier_id:supplier||null,p_reference_no:reference||null,p_notes:null});if(error){setMsg(error.message);return}setDescription('');setAmount('');setPayment('');setReference('');setMsg('Expense recorded.');await load()}
 async function voidExpense(id:string){const reason=window.prompt('Reason for voiding this expense');if(reason===null)return;const{error}=await supabase.rpc('void_expense',{p_expense_id:id,p_reason:reason});if(error){setMsg(error.message);return}setMsg('Expense voided.');await load()}
 return <><h1>Expenses</h1><p className="lead">Record operating expenses separately from inventory purchases. Ingredient purchases should normally be entered through Purchasing so stock and cost are updated correctly.</p><div className="panel"><form className="crudform" onSubmit={e=>void submit(e)}><select value={category} onChange={e=>setCategory(e.target.value)} required><option value="">Category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name_th} ({c.code})</option>)}</select><select value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">Supplier (optional)</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.supplier_name}</option>)}</select><input placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)} required/><input type="number" min="0.01" step="0.01" placeholder="Amount (THB)" value={amount} onChange={e=>setAmount(e.target.value)} required/><input placeholder="Payment method" value={payment} onChange={e=>setPayment(e.target.value)}/><input placeholder="Reference no." value={reference} onChange={e=>setReference(e.target.value)}/><button>Record Expense</button></form>{msg&&<div className="warn">{msg}</div>}</div><div className="panel"><h2>Recent expenses</h2><div className="tablewrap"><table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Supplier</th><th>Amount</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.expense_date}</td><td>{r.expense_categories?.name_th??r.expense_categories?.code??''}</td><td>{r.description}</td><td>{r.suppliers?.supplier_name??''}</td><td>฿{Number(r.amount).toFixed(2)}</td><td>{r.payment_method??''}</td><td>{r.status}</td><td>{r.status==='ACTIVE'&&<button className="smallbtn danger" onClick={()=>void voidExpense(r.id)}>Void</button>}</td></tr>)}</tbody></table></div></div></>;
}
