import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

type Inv={ingredient_id:string;ingredient_code:string;name_th:string;name_en:string|null;base_unit_id:string;current_quantity:number;current_value:number;weighted_avg_cost:number|null;minimum_stock_level:number;is_low_stock:boolean};
type Unit={id:string;code:string};
type Ingredient={id:string;name_th:string;ingredient_code:string;base_unit_id:string};

export function InventoryPage(){
 const[rows,setRows]=useState<Inv[]>([]),[units,setUnits]=useState<Unit[]>([]),[ingredients,setIngredients]=useState<Ingredient[]>([]),[msg,setMsg]=useState('');const[opening,setOpening]=useState({ingredient_id:'',quantity:'',total_cost:'',notes:''});const[processing,setProcessing]=useState(false);
 const load=useCallback(async()=>{const[a,b,c]=await Promise.all([supabase.from('inventory_summary').select('*').order('name_th'),supabase.from('units').select('id,code'),supabase.from('ingredients').select('id,name_th,ingredient_code,base_unit_id').eq('is_active',true).order('name_th')]);if(a.error)setMsg(a.error.message);setRows((a.data??[]) as Inv[]);setUnits((b.data??[]) as Unit[]);setIngredients((c.data??[]) as Ingredient[]);},[]);
 useEffect(()=>{void load()},[load]);const unit=(id:string)=>units.find(x=>x.id===id)?.code??'';
 async function recordOpening(e:React.FormEvent){e.preventDefault();setMsg('');const{data,error}=await supabase.rpc('record_opening_stock',{p_ingredient_id:opening.ingredient_id,p_quantity_base:Number(opening.quantity),p_total_cost:Number(opening.total_cost),p_notes:opening.notes||null});if(error){setMsg(error.message);return}setMsg(`Opening stock recorded: ${String(data)}`);setOpening({ingredient_id:'',quantity:'',total_cost:'',notes:''});await load()}
 async function processSales(){setProcessing(true);setMsg('');const{data,error}=await supabase.rpc('process_pending_sales_inventory',{p_sales_item_ids:null});setProcessing(false);if(error){setMsg(error.message);return}setMsg(`Sales inventory processed: ${JSON.stringify(data)}`);await load()}
 return <><h1>Stock Overview</h1><p className="lead">Current stock and value are derived from the immutable inventory movement ledger.</p><div className="panel"><h2>Opening stock</h2><p>Use this only once per ingredient before any other stock movement exists. Quantity must be entered in the ingredient base unit.</p><form className="crudform" onSubmit={e=>void recordOpening(e)}><select value={opening.ingredient_id} onChange={e=>setOpening({...opening,ingredient_id:e.target.value})} required><option value="">Ingredient</option>{ingredients.map(x=><option key={x.id} value={x.id}>{x.ingredient_code} · {x.name_th} ({unit(x.base_unit_id)})</option>)}</select><input type="number" min="0.0001" step="0.0001" placeholder="Opening quantity" value={opening.quantity} onChange={e=>setOpening({...opening,quantity:e.target.value})} required/><input type="number" min="0" step="0.01" placeholder="Opening total cost ฿" value={opening.total_cost} onChange={e=>setOpening({...opening,total_cost:e.target.value})} required/><input placeholder="Notes" value={opening.notes} onChange={e=>setOpening({...opening,notes:e.target.value})}/><button>Record opening stock</button></form></div><div className="panel"><h2>Sales → Inventory processing</h2><p>Processes matched sales only when every recipe ingredient has a valid cost basis. Missing costs remain pending instead of recording COGS as zero.</p><button onClick={()=>void processSales()} disabled={processing}>{processing?'Processing…':'Process pending sales inventory'}</button>{msg&&<p>{msg}</p>}</div><div className="panel"><h2>Inventory</h2><div className="tablewrap"><table><thead><tr><th>Code</th><th>Ingredient</th><th>Quantity</th><th>Avg cost</th><th>Stock value</th><th>Minimum</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.ingredient_id} className={r.is_low_stock?'bad':''}><td>{r.ingredient_code}</td><td>{r.name_th}</td><td>{Number(r.current_quantity).toFixed(4)} {unit(r.base_unit_id)}</td><td>{r.weighted_avg_cost==null?'Not costed':`฿${Number(r.weighted_avg_cost).toFixed(4)}`}</td><td>฿{Number(r.current_value).toFixed(2)}</td><td>{Number(r.minimum_stock_level).toFixed(4)}</td><td>{r.current_quantity<0?'NEGATIVE':r.is_low_stock?'LOW':'OK'}</td></tr>)}</tbody></table></div></div></>;
}