import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

type Inv={ingredient_id:string;ingredient_code:string;name_th:string;name_en:string|null;base_unit_id:string;current_quantity:number;current_value:number;weighted_avg_cost:number|null;minimum_stock_level:number;is_low_stock:boolean};
type Unit={id:string;code:string};
type Ingredient={id:string;name_th:string;ingredient_code:string;base_unit_id:string};

export function InventoryPage(){
 const[rows,setRows]=useState<Inv[]>([]),[units,setUnits]=useState<Unit[]>([]),[ingredients,setIngredients]=useState<Ingredient[]>([]),[msg,setMsg]=useState('');const[opening,setOpening]=useState({ingredient_id:'',quantity:'',total_cost:'',notes:''});const[processing,setProcessing]=useState(false);
 const load=useCallback(async()=>{const[a,b,c]=await Promise.all([supabase.from('inventory_summary').select('*').order('name_th'),supabase.from('units').select('id,code'),supabase.from('ingredients').select('id,name_th,ingredient_code,base_unit_id').eq('is_active',true).order('name_th')]);if(a.error)setMsg(a.error.message);setRows((a.data??[]) as Inv[]);setUnits((b.data??[]) as Unit[]);setIngredients((c.data??[]) as Ingredient[]);},[]);
 useEffect(()=>{void load()},[load]);const unit=(id:string)=>units.find(x=>x.id===id)?.code??'';
 async function recordOpening(e:React.FormEvent){e.preventDefault();setMsg('');const{data,error}=await supabase.rpc('record_opening_stock',{p_ingredient_id:opening.ingredient_id,p_quantity_base:Number(opening.quantity),p_total_cost:Number(opening.total_cost),p_notes:opening.notes||null});if(error){setMsg(error.message);return}setMsg(`บันทึกยอดยกมาสต็อกแล้ว: ${String(data)}`);setOpening({ingredient_id:'',quantity:'',total_cost:'',notes:''});await load()}
 async function processSales(){setProcessing(true);setMsg('');const{data,error}=await supabase.rpc('process_pending_sales_inventory',{p_sales_item_ids:null});setProcessing(false);if(error){setMsg(error.message);return}setMsg(`ประมวลผลตัดสต็อกจากยอดขายแล้ว: ${JSON.stringify(data)}`);await load()}
 return <><h1>ภาพรวมสต็อก</h1><p className="lead">ยอดคงเหลือและมูลค่าสต็อกคำนวณจากประวัติความเคลื่อนไหวของสต็อกในระบบ</p><div className="panel"><h2>ยอดยกมาสต็อก</h2><p>ใช้ครั้งเดียวต่อวัตถุดิบก่อนเกิดความเคลื่อนไหวสต็อกอื่น ๆ และกรอกจำนวนตามหน่วยฐานของวัตถุดิบ</p><form className="crudform" onSubmit={e=>void recordOpening(e)}><select value={opening.ingredient_id} onChange={e=>setOpening({...opening,ingredient_id:e.target.value})} required><option value="">เลือกวัตถุดิบ</option>{ingredients.map(x=><option key={x.id} value={x.id}>{x.ingredient_code} · {x.name_th} ({unit(x.base_unit_id)})</option>)}</select><input type="number" min="0.0001" step="0.0001" placeholder="จำนวนยกมา" value={opening.quantity} onChange={e=>setOpening({...opening,quantity:e.target.value})} required/><input type="number" min="0" step="0.01" placeholder="ต้นทุนรวมยกมา (บาท)" value={opening.total_cost} onChange={e=>setOpening({...opening,total_cost:e.target.value})} required/><input placeholder="หมายเหตุ" value={opening.notes} onChange={e=>setOpening({...opening,notes:e.target.value})}/><button>บันทึกยอดยกมา</button></form></div><div className="panel"><h2>ประมวลผลยอดขาย → สต็อก</h2><p>ตัดสต็อกเฉพาะรายการขายที่จับคู่สูตรแล้วและวัตถุดิบทุกตัวมีต้นทุนที่ถูกต้อง หากต้นทุนยังไม่ครบ ระบบจะค้างรายการไว้แทนการบันทึก COGS เป็นศูนย์</p><button onClick={()=>void processSales()} disabled={processing}>{processing?'กำลังประมวลผล…':'ประมวลผลยอดขายที่รอตัดสต็อก'}</button>{msg&&<p>{msg}</p>}</div><div className="panel"><h2>สต็อกคงเหลือ</h2><div className="tablewrap"><table><thead><tr><th>รหัส</th><th>วัตถุดิบ</th><th>จำนวนคงเหลือ</th><th>ต้นทุนเฉลี่ย</th><th>มูลค่าสต็อก</th><th>ขั้นต่ำ</th><th>สถานะ</th></tr></thead><tbody>{rows.map(r=><tr key={r.ingredient_id} className={r.is_low_stock?'bad':''}><td>{r.ingredient_code}</td><td>{r.name_th}</td><td>{Number(r.current_quantity).toFixed(4)} {unit(r.base_unit_id)}</td><td>{r.weighted_avg_cost==null?'ยังไม่มีต้นทุน':`฿${Number(r.weighted_avg_cost).toFixed(4)}`}</td><td>฿{Number(r.current_value).toFixed(2)}</td><td>{Number(r.minimum_stock_level).toFixed(4)}</td><td>{r.current_quantity<0?'ติดลบ':r.is_low_stock?'ใกล้หมด':'ปกติ'}</td></tr>)}</tbody></table></div></div></>;
}