import {useCallback,useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';

type Row={ingredient_id:string;ingredient_code:string|null;name_th:string|null;name_en:string|null;current_quantity:number|null;minimum_stock_level:number|null;weighted_avg_cost:number|null;current_value:number|null;base_unit_id:string|null};
type Unit={id:string;code:string};

export function LowStockPage(){
 const[rows,setRows]=useState<Row[]>([]);const[units,setUnits]=useState<Unit[]>([]);const[msg,setMsg]=useState('');const[query,setQuery]=useState('');const[selected,setSelected]=useState<Set<string>>(new Set());const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setMsg('');const[a,b]=await Promise.all([supabase.from('inventory_summary').select('ingredient_id,ingredient_code,name_th,name_en,current_quantity,minimum_stock_level,weighted_avg_cost,current_value,base_unit_id').eq('is_low_stock',true).order('name_th'),supabase.from('units').select('id,code')]);if(a.error||b.error){setMsg(a.error?.message||b.error?.message||'โหลดข้อมูลสต็อกต่ำไม่สำเร็จ');return}const loaded=(a.data??[]) as Row[];setRows(loaded);setSelected(new Set(loaded.filter(r=>Number(r.minimum_stock_level??0)>Number(r.current_quantity??0)).map(r=>r.ingredient_id)));setUnits((b.data??[]) as Unit[])},[]);
 useEffect(()=>{void load()},[load]);
 const unitMap=useMemo(()=>Object.fromEntries(units.map(u=>[u.id,u.code])),[units]);
 const filtered=rows.filter(r=>`${r.ingredient_code??''} ${r.name_th??''} ${r.name_en??''}`.toLowerCase().includes(query.toLowerCase()));
 function toggle(id:string){setSelected(prev=>{const n=new Set(prev);if(n.has(id))n.delete(id);else n.add(id);return n})}
 async function createPurchaseDraft(){const chosen=rows.filter(r=>selected.has(r.ingredient_id)&&r.base_unit_id&&Number(r.minimum_stock_level??0)>Number(r.current_quantity??0));if(chosen.length===0){setMsg('กรุณาเลือกรายการที่ต้องสั่งซื้ออย่างน้อย 1 รายการ');return}setBusy(true);setMsg('');const{data:{user}}=await supabase.auth.getUser();if(!user){setMsg('กรุณาเข้าสู่ระบบใหม่');setBusy(false);return}const purchaseNo=`SUG-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;const subtotal=chosen.reduce((s,r)=>{const q=Math.max(0,Number(r.minimum_stock_level??0)-Number(r.current_quantity??0));return s+q*Number(r.weighted_avg_cost??0)},0);const{data:p,error:pError}=await supabase.from('purchases').insert({purchase_no:purchaseNo,purchase_date:new Date().toISOString().slice(0,10),subtotal:Number(subtotal.toFixed(2)),total_amount:Number(subtotal.toFixed(2)),payment_status:'UNPAID',status:'DRAFT',notes:'สร้างอัตโนมัติจาก Low Stock Suggestion กรุณาตรวจจำนวน ราคา และผู้ขายก่อน Receive',created_by:user.id}).select('id').single();if(pError||!p){setMsg(pError?.message||'สร้างร่างจัดซื้อไม่สำเร็จ');setBusy(false);return}const items=chosen.map(r=>{const q=Math.max(0,Number(r.minimum_stock_level??0)-Number(r.current_quantity??0));const cost=Number(r.weighted_avg_cost??0);return{purchase_id:p.id,ingredient_id:r.ingredient_id,purchase_quantity:q,purchase_unit_id:r.base_unit_id!,base_quantity:q,unit_price:cost,line_total:Number((q*cost).toFixed(2)),cost_per_base_unit:cost}});const{error:iError}=await supabase.from('purchase_items').insert(items);if(iError){setMsg(`สร้างหัวรายการ ${purchaseNo} แล้ว แต่เพิ่มรายการวัตถุดิบไม่สำเร็จ: ${iError.message}`);setBusy(false);return}setMsg(`สร้างร่างจัดซื้อ ${purchaseNo} จำนวน ${items.length} รายการแล้ว กรุณาเปิดเมนูจัดซื้อเพื่อตรวจสอบก่อน Receive`);setBusy(false)}
 return <><div className="pagehead"><div><h1>วัตถุดิบใกล้หมด</h1><p className="lead">แสดงรายการที่คงเหลือต่ำกว่าหรือเท่ากับระดับขั้นต่ำ และสามารถสร้างร่างจัดซื้อได้โดยยังไม่เพิ่มสต็อกจนกว่า OWNER/MANAGER จะกด Receive</p></div><button className="secondary" onClick={()=>void load()}>รีเฟรช</button></div><div className="cards compact"><div className="card"><small>รายการที่ต้องติดตาม</small><strong>{rows.length}</strong></div><div className="card"><small>เลือกสร้างร่างจัดซื้อ</small><strong>{selected.size}</strong></div><div className="card"><small>มูลค่าสต็อกคงเหลือ</small><strong>฿{rows.reduce((s,r)=>s+Number(r.current_value??0),0).toFixed(2)}</strong></div></div><div className="panel"><div className="toolbar"><input placeholder="ค้นหาวัตถุดิบ..." value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={busy||selected.size===0} onClick={()=>void createPurchaseDraft()}>{busy?'กำลังสร้าง...':'สร้างร่างจัดซื้อจากรายการที่เลือก'}</button></div>{msg&&<div className="warn">{msg}</div>}<div className="tablewrap"><table><thead><tr><th>เลือก</th><th>รหัส</th><th>วัตถุดิบ</th><th>คงเหลือ</th><th>ขั้นต่ำ</th><th>จำนวนแนะนำ</th><th>ต้นทุนเฉลี่ย</th><th>มูลค่าคงเหลือ</th></tr></thead><tbody>{filtered.map(r=>{const current=Number(r.current_quantity??0);const min=Number(r.minimum_stock_level??0);const shortage=Math.max(0,min-current);return <tr key={r.ingredient_id} className="bad"><td><input type="checkbox" checked={selected.has(r.ingredient_id)} onChange={()=>toggle(r.ingredient_id)} disabled={shortage<=0}/></td><td>{r.ingredient_code??''}</td><td><strong>{r.name_th??r.name_en??'-'}</strong>{r.name_en&&<small className="muted block">{r.name_en}</small>}</td><td>{current.toFixed(2)} {r.base_unit_id?unitMap[r.base_unit_id]??'':''}</td><td>{min.toFixed(2)}</td><td>{shortage.toFixed(2)} {r.base_unit_id?unitMap[r.base_unit_id]??'':''}</td><td>฿{Number(r.weighted_avg_cost??0).toFixed(4)}</td><td>฿{Number(r.current_value??0).toFixed(2)}</td></tr>})}{filtered.length===0&&<tr><td colSpan={8} className="empty">ไม่มีวัตถุดิบที่เข้าเงื่อนไข</td></tr>}</tbody></table></div></div></>;
}
