import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

type Summary={period_start:string;period_end_exclusive:string;net_sales:number;cogs:number;gross_profit:number;gross_margin_pct:number;operating_expenses:number;operating_profit:number;incomplete_cogs_rows:number};
function Card({t,v}:{t:string;v:string}){return <div className="card"><small>{t}</small><strong>{v}</strong></div>}

export function ManagementDashboardPage(){
 const now=new Date();const[month,setMonth]=useState(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`);const[data,setData]=useState<Summary|null>(null);const[msg,setMsg]=useState('');
 const load=useCallback(async()=>{setMsg('');const{data:result,error}=await supabase.rpc('get_management_summary',{p_month:`${month}-01`});if(error){setData(null);setMsg(error.message);return}setData(result as unknown as Summary)},[month]);
 useEffect(()=>{void load()},[load]);
 return <><h1>รายงานกำไรเพื่อการบริหาร</h1><p className="lead">สรุปรายเดือนจากยอดขาย GPOS ต้นทุนขายย้อนหลัง และค่าใช้จ่ายดำเนินงาน โดยการจัดซื้อจะสะท้อนผ่านต้นทุนสต็อกและไม่นับซ้ำเป็นค่าใช้จ่ายดำเนินงาน</p><div className="panel"><label>เดือน <input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label> <button onClick={()=>void load()}>รีเฟรช</button>{msg&&<div className="warn">{msg}</div>}</div>{data&&<><div className="cards"><Card t="ยอดขายสุทธิ" v={`฿${Number(data.net_sales).toFixed(2)}`}/><Card t="ต้นทุนขาย (COGS)" v={`฿${Number(data.cogs).toFixed(2)}`}/><Card t="กำไรขั้นต้น" v={`฿${Number(data.gross_profit).toFixed(2)}`}/><Card t="อัตรากำไรขั้นต้น" v={`${Number(data.gross_margin_pct).toFixed(1)}%`}/><Card t="ค่าใช้จ่ายดำเนินงาน" v={`฿${Number(data.operating_expenses).toFixed(2)}`}/><Card t="กำไรจากการดำเนินงาน" v={`฿${Number(data.operating_profit).toFixed(2)}`}/></div>{Number(data.incomplete_cogs_rows)>0&&<div className="warn">ต้นทุนขายยังไม่ครบ {data.incomplete_cogs_rows} รายการ จึงยังไม่ควรถือว่ากำไรจากการดำเนินงานเป็นตัวเลขสุดท้ายจนกว่าจะคำนวณต้นทุนครบ</div>}<div className="panel"><h2>การตีความสำหรับผู้บริหาร</h2><p><strong>กำไรขั้นต้น</strong> = ยอดขายสุทธิ − ต้นทุนขายย้อนหลัง และ <strong>กำไรจากการดำเนินงาน</strong> = กำไรขั้นต้น − ค่าใช้จ่ายดำเนินงานที่บันทึกไว้ ตัวเลขนี้ใช้เพื่อการบริหารภายใน ไม่ใช่กำไรตามงบการเงินหรือแบบภาษี</p><p>ช่วงเวลา: {data.period_start} ถึงก่อน {data.period_end_exclusive}</p></div></>}</>;
}
