import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import {uiError} from '../lib/ui';

type Summary={period_start:string;period_end_exclusive:string;net_sales:number;costed_sales:number;cogs:number;gross_profit:number;gross_margin_pct:number;operating_expenses:number;operating_profit:number;incomplete_cogs_rows:number};
function Card({t,v}:{t:string;v:string}){return <div className="card"><small>{t}</small><strong>{v}</strong></div>}

export function ManagementDashboardPage(){
 const now=new Date();const[month,setMonth]=useState(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`);const[data,setData]=useState<Summary|null>(null);const[msg,setMsg]=useState('');
 const load=useCallback(async()=>{setMsg('');const{data:result,error}=await supabase.rpc('get_management_summary',{p_month:`${month}-01`});if(error){setData(null);setMsg(uiError('โหลดรายงานกำไร'));return}setData(result as unknown as Summary)},[month]);
 useEffect(()=>{void load()},[load]);
 return <><div className="pagehead"><div><h1>รายงานกำไรเพื่อการบริหาร</h1><p className="lead">สรุปรายเดือนจากยอดขาย GPOS ต้นทุนขายย้อนหลัง และค่าใช้จ่ายดำเนินงาน โดยการจัดซื้อสะท้อนผ่านต้นทุนสต็อกและไม่นับซ้ำเป็นค่าใช้จ่ายดำเนินงาน</p></div><button className="secondary" onClick={()=>void load()}>รีเฟรช</button></div><div className="panel"><label>เดือน <input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>{msg&&<div className="warn">{msg}</div>}</div>{data&&<><div className="cards"><Card t="ยอดขายสุทธิทั้งหมด" v={`฿${Number(data.net_sales).toFixed(2)}`}/><Card t="ยอดขายที่ต้นทุนครบ" v={`฿${Number(data.costed_sales).toFixed(2)}`}/><Card t="ต้นทุนขายที่คำนวณแล้ว" v={`฿${Number(data.cogs).toFixed(2)}`}/><Card t="กำไรขั้นต้น (เฉพาะต้นทุนครบ)" v={`฿${Number(data.gross_profit).toFixed(2)}`}/><Card t="อัตรากำไรขั้นต้น (เฉพาะต้นทุนครบ)" v={`${Number(data.gross_margin_pct).toFixed(1)}%`}/><Card t="ค่าใช้จ่ายดำเนินงาน" v={`฿${Number(data.operating_expenses).toFixed(2)}`}/><Card t="กำไรจากการดำเนินงานจากข้อมูลที่ต้นทุนครบ" v={`฿${Number(data.operating_profit).toFixed(2)}`}/></div>{Number(data.incomplete_cogs_rows)>0&&<div className="warn">มีรายการขายที่ต้นทุนยังไม่ครบ {data.incomplete_cogs_rows} รายการ กำไรขั้นต้นและ Margin จึงคำนวณเฉพาะยอดขายที่ต้นทุนครบ ส่วนกำไรจากการดำเนินงานยังเป็นตัวเลขชั่วคราวจนกว่าจะประมวลผลต้นทุนครบทั้งหมด</div>}<div className="panel"><h2>การตีความสำหรับผู้บริหาร</h2><p><strong>กำไรขั้นต้น</strong> = ยอดขายที่ต้นทุนครบ − ต้นทุนขายของรายการเดียวกัน และ <strong>กำไรจากการดำเนินงาน</strong> = กำไรขั้นต้นดังกล่าว − ค่าใช้จ่ายดำเนินงานทั้งหมดของเดือน วิธีนี้ป้องกันการแสดงกำไรสูงเกินจริงเมื่อยังมีรายการรอตัดสต็อกหรือต้นทุนไม่ครบ</p><p>ยอดขายทั้งหมด ฿{Number(data.net_sales).toFixed(2)} · ยอดขายที่ใช้คำนวณกำไร ฿{Number(data.costed_sales).toFixed(2)}</p><p>ช่วงรายงาน: {new Date(`${data.period_start}T00:00:00`).toLocaleDateString('th-TH')} ถึงก่อน {new Date(`${data.period_end_exclusive}T00:00:00`).toLocaleDateString('th-TH')}</p><p className="muted">รายงานนี้ใช้เพื่อการบริหารภายใน ไม่ใช่งบการเงินหรือแบบภาษี</p></div></>}</>;
}
