import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

type Purchase={id:string;purchase_no:string;purchase_date:string;supplier_id:string|null;invoice_reference:string|null;subtotal:number;total_amount:number;status:string};
type Supplier={id:string;supplier_name:string};type Ingredient={id:string;ingredient_code:string;name_th:string};type Unit={id:string;code:string};type Line={id:string;purchase_id:string;ingredient_id:string;purchase_quantity:number;purchase_unit_id:string;unit_price:number;line_total:number};
export function PurchasesPage(){const[purchases,setPurchases]=useState<Purchase[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[ingredients,setIngredients]=useState<Ingredient[]>([]),[units,setUnits]=useState<Unit[]>([]),[lines,setLines]=useState<Line[]>([]),[selected,setSelected]=useState(''),[msg,setMsg]=useState('');const[form,setForm]=useState({supplier_id:'',invoice_reference:'',notes:''});const[line,setLine]=useState({ingredient_id:'',purchase_quantity:'',purchase_unit_id:'',unit_price:''});
 const load=useCallback(async()=>{const[a,b,c,d]=await Promise.all([supabase.from('purchases').select('*').order('created_at',{ascending:false}),supabase.from('suppliers').select('id,supplier_name').eq('is_active',true),supabase.from('ingredients').select('id,ingredient_code,name_th').eq('is_active',true),supabase.from('units').select('id,code').eq('is_active',true)]);setPurchases((a.data??[]) as Purchase[]);setSuppliers((b.data??[]) as Supplier[]);setIngredients((c.data??[]) as Ingredient[]);setUnits((d.data??[]) as Unit[]);},[]);const loadLines=useCallback(async(id:string)=>{if(!id){setLines([]);return}const{data}=await supabase.from('purchase_items').select('*').eq('purchase_id',id).order('created_at');setLines((data??[]) as Line[])},[]);useEffect(()=>{void load()},[load]);useEffect(()=>{void loadLines(selected)},[selected,loadLines]);
 const supplier=(id:string|null)=>suppliers.find(x=>x.id===id)?.supplier_name??'-';const ing=(id:string)=>{const x=ingredients.find(v=>v.id===id);return x?`${x.ingredient_code} · ${x.name_th}`:id};const unit=(id:string)=>units.find(x=>x.id===id)?.code??id;
 async function createPurchase(e:React.FormEvent){e.preventDefault();const{data:user}=await supabase.auth.getUser();const purchaseNo=`PUR-${new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14)}-${Math.floor(Math.random()*900+100)}`;const{data,error}=await supabase.from('purchases').insert({purchase_no:purchaseNo,supplier_id:form.supplier_id||null,invoice_reference:form.invoice_reference||null,notes:form.notes||null,created_by:user.user?.id,status:'DRAFT'}).select('id').single();if(error){setMsg(error.message);return}setSelected(String(data.id));setMsg(`Created ${purchaseNo}`);await load()}
 async function addLine(e:React.FormEvent){e.preventDefault();if(!selected)return;const qty=Number(line.purchase_quantity),price=Number(line.unit_price);const{error}=await supabase.from('purchase_items').insert({purchase_id:selected,ingredient_id:line.ingredient_id,purchase_quantity:qty,purchase_unit_id:line.purchase_unit_id,unit_price:price,line_total:Number((qty*price).toFixed(2))});if(error){setMsg(error.message);return}setLine({ingredient_id:'',purchase_quantity:'',purchase_unit_id:'',unit_price:''});await loadLines(selected)}
 async function receive(id:string){const{data,error}=await supabase.rpc('receive_purchase',{p_purchase_id:id});if(error){setMsg(error.message);return}setMsg(`Purchase received: ${JSON.stringify(data)}`);await load();await loadLines(id)}
 return <><h1>Purchases</h1><p className="lead">Create a draft purchase, add ingredient lines, then receive it. Receiving creates positive inventory ledger entries and updates weighted-average cost.</p><div className="panel"><h2>New purchase</h2><form className="crudform" onSubmit={e=>void createPurchase(e)}><select value={form.supplier_id} onChange={e=>setForm({...form,supplier_id:e.target.value})}><option value="">Supplier optional</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.supplier_name}</option>)}</select><input placeholder="Supplier invoice reference" value={form.invoice_reference} onChange={e=>setForm({...form,invoice_reference:e.target.value})}/><input placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button>Create draft</button></form>{msg&&<p>{msg}</p>}</div><div className="panel"><h2>Purchases</h2><div className="tablewrap"><table><thead><tr><th>No.</th><th>Date</th><th>Supplier</th><th>Invoice</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>{purchases.map(p=><tr key={p.id}><td><button className="smallbtn" onClick={()=>setSelected(p.id)}>{p.purchase_no}</button></td><td>{p.purchase_date}</td><td>{supplier(p.supplier_id)}</td><td>{p.invoice_reference??'-'}</td><td>฿{Number(p.total_amount).toFixed(2)}</td><td>{p.status}</td><td>{p.status==='DRAFT'&&<button className="smallbtn" onClick={()=>void receive(p.id)}>Receive</button>}</td></tr>)}</tbody></table></div></div>{selected&&<div className="panel"><h2>Purchase items</h2><form className="crudform" onSubmit={e=>void addLine(e)}><select value={line.ingredient_id} onChange={e=>setLine({...line,ingredient_id:e.target.value})} required><option value="">Ingredient</option>{ingredients.map(x=><option key={x.id} value={x.id}>{ing(x.id)}</option>)}</select><input type="number" min="0.0001" step="0.0001" placeholder="Purchase quantity" value={line.purchase_quantity} onChange={e=>setLine({...line,purchase_quantity:e.target.value})} required/><select value={line.purchase_unit_id} onChange={e=>setLine({...line,purchase_unit_id:e.target.value})} required><option value="">Purchase unit</option>{units.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select><input type="number" min="0" step="0.0001" placeholder="Price per purchase unit" value={line.unit_price} onChange={e=>setLine({...line,unit_price:e.target.value})} required/><button>Add line</button></form><div className="tablewrap"><table><thead><tr><th>Ingredient</th><th>Qty</th><th>Unit</th><th>Unit price</th><th>Line total</th></tr></thead><tbody>{lines.map(x=><tr key={x.id}><td>{ing(x.ingredient_id)}</td><td>{x.purchase_quantity}</td><td>{unit(x.purchase_unit_id)}</td><td>฿{Number(x.unit_price).toFixed(4)}</td><td>฿{Number(x.line_total).toFixed(2)}</td></tr>)}</tbody></table></div></div>}</>}
