import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import {formatUnit} from '../lib/ui';

type Purchase={id:string;purchase_no:string;purchase_date:string;supplier_id:string|null;invoice_reference:string|null;subtotal:number;total_amount:number;status:string};
type Supplier={id:string;supplier_name:string};type Ingredient={id:string;ingredient_code:string;name_th:string};type Unit={id:string;code:string;name_th:string|null;name_en:string|null};type Line={id:string;purchase_id:string;ingredient_id:string;purchase_quantity:number;purchase_unit_id:string;unit_price:number;line_total:number};
const statusLabel:Record<string,string>={DRAFT:'ร่าง',RECEIVED:'รับสินค้าแล้ว',CANCELLED:'ยกเลิก',VOID:'ยกเลิก'};
export function PurchasesPage(){const[purchases,setPurchases]=useState<Purchase[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[ingredients,setIngredients]=useState<Ingredient[]>([]),[units,setUnits]=useState<Unit[]>([]),[lines,setLines]=useState<Line[]>([]),[selected,setSelected]=useState(''),[msg,setMsg]=useState('');const[form,setForm]=useState({supplier_id:'',invoice_reference:'',notes:''});const[line,setLine]=useState({ingredient_id:'',purchase_quantity:'',purchase_unit_id:'',unit_price:''});
 const load=useCallback(async()=>{const[a,b,c,d]=await Promise.all([supabase.from('purchases').select('*').order('created_at',{ascending:false}),supabase.from('suppliers').select('id,supplier_name').eq('is_active',true),supabase.from('ingredients').select('id,ingredient_code,name_th').eq('is_active',true),supabase.from('units').select('id,code,name_th,name_en').eq('is_active',true)]);if(a.error||b.error||c.error||d.error)setMsg('โหลดข้อมูลจัดซื้อไม่สำเร็จ กรุณาลองใหม่');setPurchases((a.data??[]) as Purchase[]);setSuppliers((b.data??[]) as Supplier[]);setIngredients((c.data??[]) as Ingredient[]);setUnits((d.data??[]) as Unit[]);},[]);const loadLines=useCallback(async(id:string)=>{if(!id){setLines([]);return}const{data,error}=await supabase.from('purchase_items').select('*').eq('purchase_id',id).order('created_at');if(error){setMsg('โหลดรายการวัตถุดิบไม่สำเร็จ กรุณาลองใหม่');return}setLines((data??[]) as Line[])},[]);useEffect(()=>{void load()},[load]);useEffect(()=>{void loadLines(selected)},[selected,loadLines]);
 const supplier=(id:string|null)=>suppliers.find(x=>x.id===id)?.supplier_name??'-';const ing=(id:string)=>{const x=ingredients.find(v=>v.id===id);return x?`${x.ingredient_code} · ${x.name_th}`:id};const unit=(id:string)=>formatUnit(units.find(v=>v.id===id),id);
 async function createPurchase(e:React.FormEvent){e.preventDefault();const{data:user}=await supabase.auth.getUser();const purchaseNo=`PUR-${new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14)}-${Math.floor(Math.random()*900+100)}`;const{data,error}=await supabase.from('purchases').insert({purchase_no:purchaseNo,supplier_id:form.supplier_id||null,invoice_reference:form.invoice_reference||null,notes:form.notes||null,created_by:user.user?.id,status:'DRAFT'}).select('id').single();if(error){setMsg('สร้างรายการจัดซื้อไม่สำเร็จ กรุณาตรวจข้อมูลและลองใหม่');return}setSelected(String(data.id));setMsg(`สร้างร่างจัดซื้อ ${purchaseNo} แล้ว`);await load()}
 async function addLine(e:React.FormEvent){e.preventDefault();if(!selected)return;const qty=Number(line.purchase_quantity),price=Number(line.unit_price);const{error}=await supabase.from('purchase_items').insert({purchase_id:selected,ingredient_id:line.ingredient_id,purchase_quantity:qty,purchase_unit_id:line.purchase_unit_id,unit_price:price,line_total:Number((qty*price).toFixed(2))});if(error){setMsg('เพิ่มรายการวัตถุดิบไม่สำเร็จ กรุณาตรวจข้อมูลและลองใหม่');return}setLine({ingredient_id:'',purchase_quantity:'',purchase_unit_id:'',unit_price:''});await loadLines(selected)}
 async function receive(id:string){const{data,error}=await supabase.rpc('receive_purchase',{p_purchase_id:id});if(error){setMsg('รับสินค้าเข้าสต็อกไม่สำเร็จ กรุณาตรวจสถานะรายการและลองใหม่');return}setMsg(`รับสินค้าเข้าสต็อกแล้ว: ${JSON.stringify(data)}`);await load();await loadLines(id)}
 return <><h1>จัดซื้อ</h1><p className="lead">สร้างร่างใบจัดซื้อ เพิ่มรายการวัตถุดิบ แล้วกดรับสินค้าเข้าสต็อก ระบบจะเพิ่มความเคลื่อนไหวสต็อกและคำนวณต้นทุนเฉลี่ยถ่วงน้ำหนัก</p><div className="panel"><h2>สร้างรายการจัดซื้อใหม่</h2><form className="crudform" onSubmit={e=>void createPurchase(e)}><select value={form.supplier_id} onChange={e=>setForm({...form,supplier_id:e.target.value})}><option value="">ซัพพลายเออร์ (ไม่บังคับ)</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.supplier_name}</option>)}</select><input placeholder="เลขที่เอกสารจากซัพพลายเออร์" value={form.invoice_reference} onChange={e=>setForm({...form,invoice_reference:e.target.value})}/><input placeholder="หมายเหตุ" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button>สร้างร่าง</button></form>{msg&&<p>{msg}</p>}</div><div className="panel"><h2>รายการจัดซื้อ</h2><div className="tablewrap"><table><thead><tr><th>เลขที่</th><th>วันที่</th><th>ซัพพลายเออร์</th><th>เลขที่ใบแจ้งหนี้</th><th>ยอดรวม</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>{purchases.map(p=><tr key={p.id}><td><button className="smallbtn" onClick={()=>setSelected(p.id)}>{p.purchase_no}</button></td><td>{p.purchase_date}</td><td>{supplier(p.supplier_id)}</td><td>{p.invoice_reference??'-'}</td><td>฿{Number(p.total_amount).toFixed(2)}</td><td>{statusLabel[p.status]??p.status}</td><td>{p.status==='DRAFT'&&<button className="smallbtn" onClick={()=>void receive(p.id)}>รับสินค้า</button>}</td></tr>)}</tbody></table></div></div>{selected&&<div className="panel"><h2>รายการวัตถุดิบในใบจัดซื้อ</h2><form className="crudform" onSubmit={e=>void addLine(e)}><select value={line.ingredient_id} onChange={e=>setLine({...line,ingredient_id:e.target.value})} required><option value="">วัตถุดิบ</option>{ingredients.map(x=><option key={x.id} value={x.id}>{ing(x.id)}</option>)}</select><input type="number" min="0.0001" step="0.0001" placeholder="จำนวนที่ซื้อ" value={line.purchase_quantity} onChange={e=>setLine({...line,purchase_quantity:e.target.value})} required/><select value={line.purchase_unit_id} onChange={e=>setLine({...line,purchase_unit_id:e.target.value})} required><option value="">หน่วยซื้อ</option>{units.map(x=><option key={x.id} value={x.id}>{unit(x.id)}</option>)}</select><input type="number" min="0" step="0.0001" placeholder="ราคาต่อหน่วยซื้อ" value={line.unit_price} onChange={e=>setLine({...line,unit_price:e.target.value})} required/><button>เพิ่มรายการ</button></form><div className="tablewrap"><table><thead><tr><th>วัตถุดิบ</th><th>จำนวน</th><th>หน่วย</th><th>ราคาต่อหน่วย</th><th>รวม</th></tr></thead><tbody>{lines.map(x=><tr key={x.id}><td>{ing(x.ingredient_id)}</td><td>{x.purchase_quantity}</td><td>{unit(x.purchase_unit_id)}</td><td>฿{Number(x.unit_price).toFixed(4)}</td><td>฿{Number(x.line_total).toFixed(2)}</td></tr>)}</tbody></table></div></div>}</>}
