import {useCallback,useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';
import {formatUnit,uiError} from '../lib/ui';

type Recipe={id:string;menu_item_id:string;recipe_name:string;version_no:number;yield_quantity:number;status:string;effective_from:string};
type RecipeItem={id:string;recipe_id:string;ingredient_id:string;quantity:number;unit_id:string;wastage_percentage:number};
type MenuItem={id:string;name_th:string;name_en:string|null;selling_price:number};
type Ingredient={id:string;name_th:string;name_en:string|null;base_unit_id:string};
type Unit={id:string;code:string;name_th:string|null;name_en:string|null};
type Conversion={from_unit_id:string;to_unit_id:string;conversion_factor:number;ingredient_id:string|null;is_active:boolean};
type StockSummary={ingredient_id:string;weighted_avg_cost:number|null;current_quantity:number};

type LineCost={ingredientName:string;quantity:number;unitName:string;baseQuantity:number|null;unitCost:number|null;lineCost:number|null;status:string};
type RecipeCost={recipe:Recipe;menuName:string;sellingPrice:number;totalCost:number|null;costPerSaleUnit:number|null;grossProfit:number|null;margin:number|null;missing:number;lines:LineCost[]};

const statusLabel:Record<string,string>={ACTIVE:'ใช้งาน',DRAFT:'ร่าง',INACTIVE:'ปิดใช้งาน'};

export function RecipeCostingPage(){
 const[recipes,setRecipes]=useState<Recipe[]>([]);const[recipeItems,setRecipeItems]=useState<RecipeItem[]>([]);const[menus,setMenus]=useState<MenuItem[]>([]);const[ingredients,setIngredients]=useState<Ingredient[]>([]);const[units,setUnits]=useState<Unit[]>([]);const[conversions,setConversions]=useState<Conversion[]>([]);const[stock,setStock]=useState<StockSummary[]>([]);const[status,setStatus]=useState('ACTIVE');const[query,setQuery]=useState('');const[selected,setSelected]=useState('');const[msg,setMsg]=useState('');
 const load=useCallback(async()=>{setMsg('');const[a,b,c,d,e,f,g]=await Promise.all([
  supabase.from('recipes').select('id,menu_item_id,recipe_name,version_no,yield_quantity,status,effective_from').order('created_at',{ascending:false}),
  supabase.from('recipe_items').select('id,recipe_id,ingredient_id,quantity,unit_id,wastage_percentage'),
  supabase.from('menu_items').select('id,name_th,name_en,selling_price'),
  supabase.from('ingredients').select('id,name_th,name_en,base_unit_id'),
  supabase.from('units').select('id,code,name_th,name_en'),
  supabase.from('unit_conversions').select('from_unit_id,to_unit_id,conversion_factor,ingredient_id,is_active').eq('is_active',true),
  supabase.from('inventory_summary').select('ingredient_id,weighted_avg_cost,current_quantity'),
 ]);if(a.error||b.error||c.error||d.error||e.error||f.error||g.error){setMsg(uiError('โหลดข้อมูลต้นทุนสูตร'));return}setRecipes((a.data??[]) as Recipe[]);setRecipeItems((b.data??[]) as RecipeItem[]);setMenus((c.data??[]) as MenuItem[]);setIngredients((d.data??[]) as Ingredient[]);setUnits((e.data??[]) as Unit[]);setConversions((f.data??[]) as Conversion[]);setStock((g.data??[]) as StockSummary[])},[]);
 useEffect(()=>{void load()},[load]);
 const menuMap=useMemo(()=>new Map(menus.map(x=>[x.id,x])),[menus]);const ingMap=useMemo(()=>new Map(ingredients.map(x=>[x.id,x])),[ingredients]);const unitMap=useMemo(()=>new Map(units.map(x=>[x.id,x])),[units]);const stockMap=useMemo(()=>new Map(stock.map(x=>[x.ingredient_id,x])),[stock]);
 function factor(ingredientId:string,from:string,to:string){if(from===to)return 1;const candidates=conversions.filter(c=>c.from_unit_id===from&&c.to_unit_id===to);const specific=candidates.find(c=>c.ingredient_id===ingredientId);const generic=candidates.find(c=>c.ingredient_id==null);return Number((specific??generic)?.conversion_factor||0)||null}
 const costs=useMemo<RecipeCost[]>(()=>recipes.map(recipe=>{const menu=menuMap.get(recipe.menu_item_id);const lines=recipeItems.filter(x=>x.recipe_id===recipe.id).map(line=>{const ing=ingMap.get(line.ingredient_id);const unit=unitMap.get(line.unit_id);if(!ing)return {ingredientName:line.ingredient_id,quantity:Number(line.quantity),unitName:formatUnit(unit),baseQuantity:null,unitCost:null,lineCost:null,status:'ไม่พบวัตถุดิบ'};const conversion=factor(line.ingredient_id,line.unit_id,ing.base_unit_id);const avg=Number(stockMap.get(line.ingredient_id)?.weighted_avg_cost||0);if(!conversion)return {ingredientName:ing.name_th||ing.name_en||line.ingredient_id,quantity:Number(line.quantity),unitName:formatUnit(unit),baseQuantity:null,unitCost:avg||null,lineCost:null,status:'ยังไม่ได้ตั้งค่าการแปลงหน่วย'};const baseQty=Number(line.quantity)*conversion*(1+Number(line.wastage_percentage||0)/100);if(avg<=0)return {ingredientName:ing.name_th||ing.name_en||line.ingredient_id,quantity:Number(line.quantity),unitName:formatUnit(unit),baseQuantity:baseQty,unitCost:null,lineCost:null,status:'ยังไม่มีต้นทุนสต็อก'};return {ingredientName:ing.name_th||ing.name_en||line.ingredient_id,quantity:Number(line.quantity),unitName:formatUnit(unit),baseQuantity:baseQty,unitCost:avg,lineCost:baseQty*avg,status:'พร้อม'};});const missing=lines.filter(x=>x.lineCost==null).length;const total=missing===0?lines.reduce((s,x)=>s+Number(x.lineCost||0),0):null;const per=total==null?null:total/Number(recipe.yield_quantity||1);const price=Number(menu?.selling_price||0);const gp=per==null?null:price-per;const margin=gp==null||price<=0?null:(gp/price)*100;return {recipe,menuName:menu?.name_th||menu?.name_en||'ไม่พบชื่อเมนู',sellingPrice:price,totalCost:total,costPerSaleUnit:per,grossProfit:gp,margin,missing,lines}}),[recipes,recipeItems,menuMap,ingMap,unitMap,stockMap,conversions]);
 const filtered=useMemo(()=>costs.filter(x=>(status==='ALL'||x.recipe.status===status)&&(!query||`${x.menuName} ${x.recipe.recipe_name}`.toLowerCase().includes(query.toLowerCase()))),[costs,status,query]);
 const selectedCost=costs.find(x=>x.recipe.id===selected)||null;
 return <><div className="pagehead"><div><h1>ต้นทุนสูตร</h1><p className="lead">คำนวณต้นทุนสูตรจากปริมาณวัตถุดิบในสูตร การสูญเสีย การแปลงหน่วย และต้นทุนเฉลี่ยของสต็อกปัจจุบัน เพื่อใช้ตรวจความพร้อมก่อนตัดสต็อกจากยอดขาย</p></div><button className="secondary" onClick={()=>void load()}>รีเฟรช</button></div><div className="panel"><div className="toolbar"><input placeholder="ค้นหาเมนูหรือชื่อสูตร..." value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">สูตรที่ใช้งาน</option><option value="DRAFT">สูตรร่าง</option><option value="INACTIVE">สูตรปิดใช้งาน</option><option value="ALL">ทุกสถานะ</option></select><button className="secondary" onClick={()=>{setQuery('');setStatus('ACTIVE')}}>ล้างตัวกรอง</button></div>{msg&&<div className="warn">{msg}</div>}<div className="tablewrap"><table><thead><tr><th>เมนู</th><th>สูตร</th><th>เวอร์ชัน</th><th>สถานะ</th><th>ราคาขาย</th><th>ต้นทุน/หน่วยขาย</th><th>กำไรขั้นต้น/หน่วย</th><th>Margin</th><th>ความพร้อม</th><th>รายละเอียด</th></tr></thead><tbody>{filtered.map(x=><tr key={x.recipe.id}><td><strong>{x.menuName}</strong></td><td>{x.recipe.recipe_name}</td><td>{x.recipe.version_no}</td><td>{statusLabel[x.recipe.status]??x.recipe.status}</td><td>฿{x.sellingPrice.toFixed(2)}</td><td>{x.costPerSaleUnit==null?'—':`฿${x.costPerSaleUnit.toFixed(2)}`}</td><td>{x.grossProfit==null?'—':`฿${x.grossProfit.toFixed(2)}`}</td><td>{x.margin==null?'—':`${x.margin.toFixed(1)}%`}</td><td>{x.missing===0?'พร้อมคำนวณ':`ข้อมูลไม่ครบ ${x.missing} รายการ`}</td><td><button className="smallbtn" onClick={()=>setSelected(x.recipe.id)}>ดูสูตรต้นทุน</button></td></tr>)}{filtered.length===0&&<tr><td colSpan={10} className="empty">ไม่พบสูตรตามเงื่อนไข</td></tr>}</tbody></table></div></div>{selectedCost&&<div className="panel"><h2>{selectedCost.menuName} — {selectedCost.recipe.recipe_name}</h2><p>ผลผลิตต่อสูตร: {Number(selectedCost.recipe.yield_quantity).toFixed(4)} หน่วยขาย · ต้นทุนรวมสูตร: {selectedCost.totalCost==null?'ข้อมูลยังไม่ครบ':`฿${selectedCost.totalCost.toFixed(2)}`}</p>{selectedCost.missing>0&&<div className="warn">สูตรนี้ยังไม่พร้อมคำนวณต้นทุนครบ กรุณาตรวจรายการที่มีสถานะผิดปกติด้านล่างก่อนนำยอดขายไปตัดสต็อก</div>}<div className="tablewrap"><table><thead><tr><th>วัตถุดิบ</th><th>ปริมาณในสูตร</th><th>ปริมาณหน่วยฐานรวมสูญเสีย</th><th>ต้นทุนเฉลี่ย/หน่วยฐาน</th><th>ต้นทุนในสูตร</th><th>สถานะ</th></tr></thead><tbody>{selectedCost.lines.map((l,i)=><tr key={`${l.ingredientName}-${i}`}><td>{l.ingredientName}</td><td>{l.quantity.toFixed(4)} {l.unitName}</td><td>{l.baseQuantity==null?'—':l.baseQuantity.toFixed(4)}</td><td>{l.unitCost==null?'—':`฿${l.unitCost.toFixed(4)}`}</td><td>{l.lineCost==null?'—':`฿${l.lineCost.toFixed(2)}`}</td><td>{l.status}</td></tr>)}{selectedCost.lines.length===0&&<tr><td colSpan={6} className="empty">สูตรนี้ยังไม่มีวัตถุดิบ</td></tr>}</tbody></table></div></div>}</>;
}
