import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import {uiError} from '../lib/ui';

type Totals={net:number;processedSales:number;cogs:number;invoices:number;items:number;pending:number;missing:number};

export function SalesOverviewPage(){
 const[t,setT]=useState<Totals>({net:0,processedSales:0,cogs:0,invoices:0,items:0,pending:0,missing:0});const[msg,setMsg]=useState('');
 const load=useCallback(async()=>{setMsg('');const[tx,si]=await Promise.all([supabase.from('sales_transactions').select('id,net_amount,status'),supabase.from('sales_items').select('sales_transaction_id,quantity,net_amount,total_cost_snapshot,costing_status')]);if(tx.error||si.error){setMsg(uiError('โหลดภาพรวมยอดขาย'));return}const txs=(tx.data??[]).filter(x=>x.status!=='REVERSED');const validTx=new Set(txs.map(x=>x.id));const items=(si.data??[]).filter(x=>validTx.has(x.sales_transaction_id));const processed=items.filter(x=>x.costing_status==='PROCESSED'&&x.total_cost_snapshot!=null);setT({net:txs.reduce((a,x)=>a+Number(x.net_amount||0),0),processedSales:processed.reduce((a,x)=>a+Number(x.net_amount||0),0),cogs:processed.reduce((a,x)=>a+Number(x.total_cost_snapshot||0),0),invoices:txs.length,items:items.reduce((a,x)=>a+Number(x.quantity||0),0),pending:items.filter(x=>x.costing_status==='PENDING').length,missing:items.filter(x=>x.costing_status==='MISSING_COST'||x.costing_status==='ERROR').length})},[]);
 useEffect(()=>{void load()},[load]);
 const gp=t.processedSales-t.cogs;const margin=t.processedSales>0?gp/t.processedSales*100:0;
 return <><div className="pagehead"><div><h1>ภาพรวมยอดขาย</h1><p className="lead">สรุปยอดขายและต้นทุนขายย้อนหลังจากต้นทุนที่ถูกบันทึก ณ วันที่ระบบประมวลผลการใช้วัตถุดิบ</p></div><button className="secondary" onClick={()=>void load()}>รีเฟรช</button></div><div className="cards"><Card t="ยอดขายสุทธิทั้งหมด" v={`฿${t.net.toFixed(2)}`}/><Card t="ยอดขายที่ต้นทุนครบ" v={`฿${t.processedSales.toFixed(2)}`}/><Card t="ต้นทุนขายที่คำนวณแล้ว" v={`฿${t.cogs.toFixed(2)}`}/><Card t="กำไรขั้นต้น (เฉพาะต้นทุนครบ)" v={`฿${gp.toFixed(2)}`}/><Card t="อัตรากำไรขั้นต้น (เฉพาะต้นทุนครบ)" v={`${margin.toFixed(1)}%`}/><Card t="จำนวนใบขาย" v={String(t.invoices)}/><Card t="จำนวนสินค้าที่ขาย" v={String(t.items)}/></div>{(t.pending>0||t.missing>0)&&<div className="warn">ข้อมูลต้นทุนขายยังไม่ครบ: รอตัดสต็อก {t.pending} รายการ และต้นทุนขาด/ต้องตรวจสอบ {t.missing} รายการ ตัวเลขกำไรจึงคำนวณเฉพาะรายการที่ต้นทุนครบ</div>}{msg&&<div className="warn">{msg}</div>}<div className="panel"><h2>การตีความ</h2><p>กำไรขั้นต้นใช้ยอดขายและต้นทุนย้อนหลังเฉพาะรายการที่คำนวณต้นทุนสมบูรณ์แล้ว จึงไม่แสดงกำไรสูงเกินจริงเมื่อยังมีรายการรอตัดสต็อก การเปลี่ยนราคาวัตถุดิบภายหลังจะไม่ย้อนกลับไปแก้ต้นทุนขายของงวดก่อน</p></div></>;
}
function Card({t,v}:{t:string;v:string}){return <div className="card"><small>{t}</small><strong>{v}</strong></div>}
