import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

type Count={id:string;count_date:string;status:string;started_at:string;completed_at:string|null;notes:string|null};
type CountItem={id:string;ingredient_id:string;expected_quantity:number;actual_quantity:number|null;variance_quantity:number|null;variance_percentage:number|null;unit_id:string;ingredients?:{name_th?:string;name_en?:string}|null;units?:{code?:string}|null};
const statusLabel:Record<string,string>={DRAFT:'กำลังตรวจนับ',COMPLETED:'เสร็จสิ้น',CANCELLED:'ยกเลิก'};
const unitLabel:Record<string,string>={G:'กรัม',GRAM:'กรัม',KG:'กิโลกรัม',KILOGRAM:'กิโลกรัม',ML:'มิลลิลิตร',MILLILITER:'มิลลิลิตร',L:'ลิตร',LITER:'ลิตร',PCS:'ชิ้น',PC:'ชิ้น',PIECE:'ชิ้น',EA:'ชิ้น',EACH:'ชิ้น',PACK:'แพ็ก',BAG:'ถุง',BOTTLE:'ขวด',CAN:'กระป๋อง',BOX:'กล่อง'};
const displayUnit=(code?:string)=>code?(unitLabel[code.toUpperCase()]??code):'';

export function StockCountPage(){
 const[counts,setCounts]=useState<Count[]>([]);const[selected,setSelected]=useState<string>('');const[items,setItems]=useState<CountItem[]>([]);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
 const loadCounts=useCallback(async()=>{const{data,error}=await supabase.from('stock_counts').select('id,count_date,status,started_at,completed_at,notes').order('started_at',{ascending:false}).limit(20);if(error){setMsg('โหลดประวัติการตรวจนับไม่สำเร็จ กรุณาลองใหม่');return}const rows=(data??[]) as Count[];setCounts(rows);if(!selected&&rows[0])setSelected(rows[0].id)},[selected]);
 const loadItems=useCallback(async()=>{if(!selected){setItems([]);return}const{data,error}=await supabase.from('stock_count_items').select('id,ingredient_id,expected_quantity,actual_quantity,variance_quantity,variance_percentage,unit_id,ingredients(name_th,name_en),units(code)').eq('stock_count_id',selected).order('created_at');if(error){setMsg('โหลดรายการวัตถุดิบสำหรับตรวจนับไม่สำเร็จ กรุณาลองใหม่');return}setItems((data??[]) as unknown as CountItem[])},[selected]);
 useEffect(()=>{void loadCounts()},[loadCounts]);useEffect(()=>{void loadItems()},[loadItems]);
 async function start(){setBusy(true);setMsg('');const{data,error}=await supabase.rpc('create_stock_count',{p_count_date:new Date().toISOString().slice(0,10),p_notes:null});setBusy(false);if(error){setMsg('เริ่มรอบตรวจนับไม่สำเร็จ กรุณาตรวจสอบว่ามีรอบที่ยังไม่ปิดอยู่หรือไม่');return}setSelected(String(data));setMsg('เริ่มรอบตรวจนับแล้ว กรุณากรอกจำนวนที่นับได้จริง');await loadCounts()}
 async function saveActual(item:CountItem,value:string){const n=Number(value);if(!Number.isFinite(n)||n<0){setMsg('จำนวนจริงต้องเป็น 0 หรือมากกว่า');return}const{error}=await supabase.from('stock_count_items').update({actual_quantity:n}).eq('id',item.id);if(error){setMsg('บันทึกจำนวนจริงไม่สำเร็จ กรุณาลองใหม่');return}setItems(x=>x.map(r=>r.id===item.id?{...r,actual_quantity:n}:r));setMsg('บันทึกจำนวนจริงแล้ว')}
 async function finalise(){if(!selected)return;setBusy(true);setMsg('');const{data,error}=await supabase.rpc('finalize_stock_count',{p_stock_count_id:selected});setBusy(false);if(error){setMsg('ปิดรอบตรวจนับไม่สำเร็จ กรุณาตรวจสอบว่ากรอกจำนวนจริงครบทุกวัตถุดิบแล้ว');return}setMsg(`ปิดรอบตรวจนับเรียบร้อย ปรับยอดสต็อก ${String((data as {adjusted_items?:number}|null)?.adjusted_items??0)} รายการ`);await loadCounts();await loadItems()}
 const current=counts.find(x=>x.id===selected);
 return <><h1>ตรวจนับสต็อก</h1><p className="lead">เปรียบเทียบยอดคงเหลือตามระบบกับจำนวนที่ตรวจนับได้จริง เมื่อปิดรอบ ระบบจะบันทึกรายการปรับยอดจากการตรวจนับไว้ในประวัติความเคลื่อนไหวสต็อก เพื่อให้ตรวจสอบย้อนหลังได้</p><div className="panel"><button onClick={()=>void start()} disabled={busy||counts.some(x=>x.status==='DRAFT')}>เริ่มตรวจนับสต็อก</button>{counts.some(x=>x.status==='DRAFT')&&<p>มีรอบตรวจนับที่ยังไม่เสร็จ กรุณาปิดรอบเดิมก่อนเริ่มรอบใหม่</p>}{msg&&<div className="warn">{msg}</div>}</div><div className="panel"><h2>ประวัติการตรวจนับ</h2><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">เลือกรอบตรวจนับ</option>{counts.map(c=><option key={c.id} value={c.id}>{c.count_date} · {statusLabel[c.status]??c.status}</option>)}</select>{current&&<p>สถานะ: <strong>{statusLabel[current.status]??current.status}</strong></p>}<div className="tablewrap"><table><thead><tr><th>วัตถุดิบ</th><th>ตามระบบ</th><th>นับจริง</th><th>ผลต่าง</th><th>ผลต่าง %</th><th>หน่วย</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.ingredients?.name_th||i.ingredients?.name_en||i.ingredient_id}</td><td>{Number(i.expected_quantity).toFixed(4)}</td><td>{current?.status==='DRAFT'?<input type="number" min="0" step="0.0001" defaultValue={i.actual_quantity??''} onBlur={e=>void saveActual(i,e.target.value)}/>:Number(i.actual_quantity??0).toFixed(4)}</td><td>{i.variance_quantity==null?'—':Number(i.variance_quantity).toFixed(4)}</td><td>{i.variance_percentage==null?'—':`${Number(i.variance_percentage).toFixed(2)}%`}</td><td>{displayUnit(i.units?.code)}</td></tr>)}</tbody></table></div>{current?.status==='DRAFT'&&<button onClick={()=>void finalise()} disabled={busy}>ยืนยันและปิดรอบตรวจนับ</button>}</div></>;
}
