import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import {uiError} from '../lib/ui';

type Role='OWNER'|'MANAGER'|'STAFF';
type UserRow={id:string;email:string;full_name:string|null;display_name:string|null;role:Role;is_active:boolean;last_sign_in_at:string|null;created_at:string|null};

const roleLabel:Record<Role,string>={OWNER:'เจ้าของร้าน',MANAGER:'ผู้จัดการ',STAFF:'พนักงาน'};
const roleInputMap:Record<string,Role>={OWNER:'OWNER',MANAGER:'MANAGER',STAFF:'STAFF','เจ้าของร้าน':'OWNER','ผู้จัดการ':'MANAGER','พนักงาน':'STAFF'};

async function callAdmin(body:Record<string,unknown>){const{data,error}=await supabase.functions.invoke('user-admin',{body});if(error)throw new Error('ADMIN_FUNCTION_ERROR');if(data?.error)throw new Error(String(data.error));return data}
function adminError(action:string,e:unknown){const text=e instanceof Error?e.message:'';if(/already|exists|registered|duplicate/i.test(text))return 'อีเมลนี้มีผู้ใช้งานอยู่แล้ว';if(/password/i.test(text))return 'รหัสผ่านไม่เป็นไปตามเงื่อนไข กรุณาใช้รหัสผ่านอย่างน้อย 8 ตัวอักษร';if(/permission|forbidden|unauthor|owner/i.test(text))return 'ไม่มีสิทธิ์ดำเนินการนี้';return uiError(action)}

export function UserManagementPage(){
 const[rows,setRows]=useState<UserRow[]>([]);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[name,setName]=useState('');const[role,setRole]=useState<Role>('STAFF');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setMsg('');try{const data=await callAdmin({action:'list'});setRows((data.users??[]) as UserRow[])}catch(e){setMsg(adminError('โหลดผู้ใช้งาน',e))}},[]);
 useEffect(()=>{void load()},[load]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');try{await callAdmin({action:'create',email:email.trim(),password,full_name:name.trim(),role});setEmail('');setPassword('');setName('');setRole('STAFF');setMsg('สร้างผู้ใช้งานเรียบร้อยแล้ว');await load()}catch(e){setMsg(adminError('สร้างผู้ใช้งาน',e))}finally{setBusy(false)}}
 async function changeRole(id:string,current:Role){const entered=window.prompt('เลือกสิทธิ์ใหม่: เจ้าของร้าน, ผู้จัดการ หรือ พนักงาน',roleLabel[current])?.trim();if(!entered)return;const next=roleInputMap[entered]??roleInputMap[entered.toUpperCase()];if(!next){setMsg('กรุณาระบุสิทธิ์เป็น เจ้าของร้าน, ผู้จัดการ หรือ พนักงาน');return}try{await callAdmin({action:'update_role',user_id:id,role:next});setMsg('อัปเดตสิทธิ์เรียบร้อยแล้ว');await load()}catch(e){setMsg(adminError('อัปเดตสิทธิ์',e))}}
 async function resetPassword(id:string){const next=window.prompt('รหัสผ่านใหม่อย่างน้อย 8 ตัวอักษร');if(!next)return;if(next.length<8){setMsg('รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร');return}try{await callAdmin({action:'reset_password',user_id:id,password:next});setMsg('เปลี่ยนรหัสผ่านเรียบร้อยแล้ว')}catch(e){setMsg(adminError('เปลี่ยนรหัสผ่าน',e))}}
 async function setActive(id:string,active:boolean){if(!window.confirm(active?'เปิดใช้งานผู้ใช้นี้?':'ปิดใช้งานผู้ใช้นี้?'))return;try{await callAdmin({action:'set_active',user_id:id,is_active:active});setMsg(active?'เปิดใช้งานแล้ว':'ปิดใช้งานแล้ว');await load()}catch(e){setMsg(adminError('เปลี่ยนสถานะผู้ใช้งาน',e))}}
 return <><div className="pagehead"><div><h1>จัดการผู้ใช้งาน</h1><p className="lead">เฉพาะเจ้าของร้านเท่านั้นที่สร้างผู้ใช้ เปลี่ยนสิทธิ์ รีเซ็ตรหัสผ่าน หรือปิดบัญชีได้</p></div><button className="secondary" onClick={()=>void load()}>รีเฟรช</button></div><div className="panel"><h2>เพิ่มผู้ใช้งาน</h2><form className="crudform" onSubmit={e=>void create(e)}><input type="email" placeholder="อีเมล" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" minLength={8} placeholder="รหัสผ่านเริ่มต้น" value={password} onChange={e=>setPassword(e.target.value)} required/><input placeholder="ชื่อ-นามสกุล" value={name} onChange={e=>setName(e.target.value)} required/><select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="STAFF">พนักงาน</option><option value="MANAGER">ผู้จัดการ</option><option value="OWNER">เจ้าของร้าน</option></select><button disabled={busy}>{busy?'กำลังสร้าง...':'เพิ่มผู้ใช้งาน'}</button></form>{msg&&<div className="warn">{msg}</div>}</div><div className="panel"><h2>ผู้ใช้งานทั้งหมด</h2><div className="tablewrap"><table><thead><tr><th>ชื่อ</th><th>อีเมล</th><th>สิทธิ์</th><th>สถานะ</th><th>เข้าใช้ล่าสุด</th><th>จัดการ</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.full_name||r.display_name||'-'}</td><td>{r.email}</td><td><span className="badge">{roleLabel[r.role]}</span></td><td>{r.is_active?'ใช้งาน':'ปิดใช้งาน'}</td><td>{r.last_sign_in_at?new Date(r.last_sign_in_at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'}):'-'}</td><td className="actions"><button className="smallbtn" onClick={()=>void changeRole(r.id,r.role)}>เปลี่ยนสิทธิ์</button><button className="smallbtn" onClick={()=>void resetPassword(r.id)}>รหัสผ่าน</button><button className={`smallbtn ${r.is_active?'danger':''}`} onClick={()=>void setActive(r.id,!r.is_active)}>{r.is_active?'ปิด':'เปิด'}</button></td></tr>)}{rows.length===0&&<tr><td colSpan={6} className="empty">ยังไม่มีผู้ใช้งานที่แสดงได้</td></tr>}</tbody></table></div></div></>;
}
