import {useCallback,useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';
import {formatUnit,uiError} from '../lib/ui';

type Ingredient={id:string;name_th:string;name_en:string|null;base_unit_id:string};
type Unit={id:string;code:string;name_th:string|null;name_en:string|null};
type Waste={id:string;quantity:number;quantity_base_unit:number;reason_code:string;notes:string|null;occurred_at:string;ingredients?:{name_th?:string;base_unit_id?:string}|null;units?:{code?:string;name_th?:string|null;name_en?:string|null}|null};
const reasons=[['EXPIRED','หมดอายุ'],['SPILLAGE','หก / สูญเสีย'],['PREPARATION_ERROR','ชงหรือเตรียมผิด'],['QUALITY_ISSUE','คุณภาพไม่ผ่าน'],['DAMAGED','เสียหาย'],['STAFF_DRINK','เครื่องดื่มพนักงาน'],['COMPLIMENTARY','ให้ลูกค้าฟรี'],['OTHER','อื่น ๆ']] as const;
const reasonMap=Object.fromEntries(reasons);

export function WastePage(){
 const[ingredients,setIngredients]=useState<Ingredient[]>([]);const[units,setUnits]=useState<Unit[]>([]);const[rows,setRows]=useState<Waste[]>([]);const[ingredient,setIngredient]=useState('');const[unit,setUnit]=useState('');const[qty,setQty]=useState('');const[reason,setReason]=useState('PREPARATION_ERROR');const[notes,setNotes]=useState('');const[msg,setMsg]=useState('');
 const load=useCallback(async()=>{setMsg('');const[a,b,c]=await Promise.all([supabase.from('ingredients').select('id,name_th,name_en,base_unit_id').eq('is_active',true).eq('track_stock',true).order('name_th'),supabase.from('units').select('id,code,name_th,name_en').eq('is_active',true).order('code'),supabase.from('waste_records').select('id,quantity,quantity_base_unit,reason_code,notes,occurred_at,ingredients(name_th,base_unit_id),units(code,name_th,name_en)').order('occurred_at',{ascending:false}).limit(100)]);if(a.error||b.error||c.error){setMsg(uiError('โหลดข้อมูลของเสีย'));return}setIngredients((a.data??[]) as Ingredient[]);setUnits((b.data??[]) as Unit[]);setRows((c.data??[]) as unknown as Waste[])},[]);
 useEffect(()=>{void load()},[load]);
 const unitMap=useMemo(()=>new Map(units.map(u=>[u.id,u])),[units]);
 function chooseIngredient(id:string){setIngredient(id);const i=ingredients.find(x=>x.id===id);if(i)setUnit(i.base_unit_id)}
 async function submit(e:React.FormEvent){e.preventDefault();setMsg('');const n=Number(qty);if(!ingredient||!unit||!Number.isFinite(n)||n<=0){setMsg('กรุณาเลือกวัตถุดิบ หน่วย และระบุจำนวนมากกว่า 0');return}const{error}=await supabase.rpc('record_waste',{p_ingredient_id:ingredient,p_quantity:n,p_unit_id:unit,p_reason_code:reason,p_notes:notes||null,p_occurred_at:new Date().toISOString()});if(error){setMsg(uiError('บันทึกของเสีย'));return}setQty('');setNotes('');setMsg('บันทึกของเสียและตัดสต็อกเรียบร้อยแล้ว');await load()}
 return <><div className="pagehead"><div><h1>ของเสียและการสูญเสีย</h1><p className="lead">บันทึกวัตถุดิบหมดอายุ หก เสียหาย ชงผิด หรือใช้เพื่อพนักงาน/ลูกค้าฟรี ระบบจะตัดจำนวนออกจากสต็อกและเก็บประวัติให้ตรวจสอบย้อนหลัง</p></div><button className="secondary" onClick={()=>void load()}>รีเฟรช</button></div><div className="panel"><form className="crudform" onSubmit={e=>void submit(e)}><select value={ingredient} onChange={e=>chooseIngredient(e.target.value)} required><option value="">เลือกวัตถุดิบ</option>{ingredients.map(i=><option key={i.id} value={i.id}>{i.name_th||i.name_en}</option>)}</select><input type="number" min="0.0001" step="0.0001" placeholder="จำนวน" value={qty} onChange={e=>setQty(e.target.value)} required/><select value={unit} onChange={e=>setUnit(e.target.value)} required><option value="">หน่วย</option>{units.map(u=><option key={u.id} value={u.id}>{formatUnit(u)}</option>)}</select><select value={reason} onChange={e=>setReason(e.target.value)}>{reasons.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select><input placeholder="หมายเหตุ" value={notes} onChange={e=>setNotes(e.target.value)}/><button>บันทึกของเสีย</button></form>{msg&&<div className="warn">{msg}</div>}</div><div className="panel"><h2>รายการล่าสุด</h2><div className="tablewrap"><table><thead><tr><th>วัน-เวลา</th><th>วัตถุดิบ</th><th>จำนวนที่กรอก</th><th>จำนวนตามหน่วยฐาน</th><th>สาเหตุ</th><th>หมายเหตุ</th></tr></thead><tbody>{rows.map(r=>{const baseUnit=r.ingredients?.base_unit_id?unitMap.get(r.ingredients.base_unit_id):undefined;return <tr key={r.id}><td>{new Date(r.occurred_at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})}</td><td>{r.ingredients?.name_th??''}</td><td>{Number(r.quantity).toFixed(4)} {formatUnit(r.units)}</td><td>{Number(r.quantity_base_unit).toFixed(4)} {formatUnit(baseUnit)}</td><td>{reasonMap[r.reason_code]??'อื่น ๆ'}</td><td>{r.notes??'—'}</td></tr>})}{rows.length===0&&<tr><td colSpan={6} className="empty">ยังไม่มีรายการของเสีย</td></tr>}</tbody></table></div></div></>;
}
