import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

type Ingredient={id:string;name_th:string;name_en:string|null;base_unit_id:string};
type Unit={id:string;code:string};
type Waste={id:string;quantity:number;quantity_base_unit:number;reason_code:string;notes:string|null;occurred_at:string;ingredients?:{name_th?:string}|null;units?:{code?:string}|null};
const reasons=['EXPIRED','SPILLAGE','PREPARATION_ERROR','QUALITY_ISSUE','DAMAGED','STAFF_DRINK','COMPLIMENTARY','OTHER'];

export function WastePage(){
 const[ingredients,setIngredients]=useState<Ingredient[]>([]);const[units,setUnits]=useState<Unit[]>([]);const[rows,setRows]=useState<Waste[]>([]);const[ingredient,setIngredient]=useState('');const[unit,setUnit]=useState('');const[qty,setQty]=useState('');const[reason,setReason]=useState('PREPARATION_ERROR');const[notes,setNotes]=useState('');const[msg,setMsg]=useState('');
 const load=useCallback(async()=>{const[a,b,c]=await Promise.all([supabase.from('ingredients').select('id,name_th,name_en,base_unit_id').eq('is_active',true).eq('track_stock',true).order('name_th'),supabase.from('units').select('id,code').eq('is_active',true).order('code'),supabase.from('waste_records').select('id,quantity,quantity_base_unit,reason_code,notes,occurred_at,ingredients(name_th),units(code)').order('occurred_at',{ascending:false}).limit(50)]);if(a.error||b.error||c.error){setMsg(a.error?.message||b.error?.message||c.error?.message||'Unable to load waste data');return}setIngredients((a.data??[]) as Ingredient[]);setUnits((b.data??[]) as Unit[]);setRows((c.data??[]) as unknown as Waste[])},[]);
 useEffect(()=>{void load()},[load]);
 function chooseIngredient(id:string){setIngredient(id);const i=ingredients.find(x=>x.id===id);if(i)setUnit(i.base_unit_id)}
 async function submit(e:React.FormEvent){e.preventDefault();setMsg('');const n=Number(qty);if(!ingredient||!unit||!Number.isFinite(n)||n<=0){setMsg('Select an ingredient, unit and quantity greater than zero.');return}const{error}=await supabase.rpc('record_waste',{p_ingredient_id:ingredient,p_quantity:n,p_unit_id:unit,p_reason_code:reason,p_notes:notes||null,p_occurred_at:new Date().toISOString()});if(error){setMsg(error.message);return}setQty('');setNotes('');setMsg('Waste recorded and inventory ledger updated.');await load()}
 return <><h1>Waste</h1><p className="lead">Record expired, spilled, damaged or preparation-loss ingredients. Waste always creates a negative inventory movement.</p><div className="panel"><form className="crudform" onSubmit={e=>void submit(e)}><select value={ingredient} onChange={e=>chooseIngredient(e.target.value)} required><option value="">Ingredient</option>{ingredients.map(i=><option key={i.id} value={i.id}>{i.name_th||i.name_en}</option>)}</select><input type="number" min="0.0001" step="0.0001" placeholder="Quantity" value={qty} onChange={e=>setQty(e.target.value)} required/><select value={unit} onChange={e=>setUnit(e.target.value)} required><option value="">Unit</option>{units.map(u=><option key={u.id} value={u.id}>{u.code}</option>)}</select><select value={reason} onChange={e=>setReason(e.target.value)}>{reasons.map(r=><option key={r}>{r}</option>)}</select><input placeholder="Notes" value={notes} onChange={e=>setNotes(e.target.value)}/><button>Record Waste</button></form>{msg&&<div className="warn">{msg}</div>}</div><div className="panel"><h2>Recent waste</h2><div className="tablewrap"><table><thead><tr><th>Date-Time</th><th>Ingredient</th><th>Entered Qty</th><th>Base Qty</th><th>Reason</th><th>Notes</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.occurred_at).toLocaleString()}</td><td>{r.ingredients?.name_th??''}</td><td>{r.quantity} {r.units?.code??''}</td><td>{Number(r.quantity_base_unit).toFixed(4)}</td><td>{r.reason_code}</td><td>{r.notes??''}</td></tr>)}</tbody></table></div></div></>;
}
