import { useCallback, useEffect, useState } from 'react';
import { NavLink, Route, Routes } from 'react-router-dom';
import { supabase, isSupabaseConfigured } from './lib/supabase';
import { GposImportPage } from './pages/GposImportPage';
import { ImportHistoryPage } from './pages/ImportHistoryPage';
import { SalesTransactionsPage } from './pages/SalesTransactionsPage';
import { RecipePage } from './pages/RecipePage';
import { InventoryPage } from './pages/InventoryPage';
import { SalesOverviewPage } from './pages/SalesOverviewPage';

const sections = [
  ['Dashboard','/'],['Sales Overview','/sales'],['Transactions','/sales/transactions'],['Import GPOS','/sales/import'],['Import History','/sales/import-history'],
  ['Menu Items','/menu'],['Recipes','/recipes'],['Recipe Costing','/recipe-costing'],['Stock Overview','/inventory'],['Stock Movements','/inventory/movements'],
  ['Stock Count','/inventory/count'],['Waste','/inventory/waste'],['Low Stock','/inventory/low'],['Purchases','/purchasing'],['Suppliers','/suppliers'],
  ['Expenses','/expenses'],['Reports','/reports'],['Units','/settings/units'],['Menu Categories','/settings/categories'],['Ingredients','/ingredients'],['Settings','/settings']
] as const;

function Shell(){return <div className="app"><aside><div className="brand">INFLOW<span>Riverside Café</span></div><nav>{sections.map(([n,p])=><NavLink key={p} to={p} end={p==='/' }>{n}</NavLink>)}</nav><button className="smallbtn" onClick={()=>void supabase.auth.signOut()}>Sign out</button></aside><main><Routes>
<Route path="/" element={<Dashboard/>}/><Route path="/sales" element={<SalesOverviewPage/>}/><Route path="/sales/transactions" element={<SalesTransactionsPage/>}/><Route path="/sales/import" element={<GposImportPage/>}/><Route path="/sales/import-history" element={<ImportHistoryPage/>}/><Route path="/recipes" element={<RecipePage/>}/><Route path="/recipe-costing" element={<SalesOverviewPage/>}/><Route path="/inventory" element={<InventoryPage/>}/>
<Route path="/menu" element={<MasterData title="Menu Items" table="menu_items" fields={['name_th','name_en','selling_price']}/>}/><Route path="/suppliers" element={<MasterData title="Suppliers" table="suppliers" fields={['supplier_name','phone','email']}/>}/><Route path="/settings/units" element={<MasterData title="Units" table="units" fields={['code','name_th','name_en','unit_type']}/>}/><Route path="/settings/categories" element={<MasterData title="Menu Categories" table="menu_categories" fields={['name_th','name_en','display_order']}/>}/><Route path="/ingredients" element={<MasterData title="Ingredients" table="ingredients" fields={['ingredient_code','name_th','name_en','base_unit_id']}/>}/><Route path="/settings" element={<Settings/>}/>
{sections.filter(([,p])=>!['/','/sales','/sales/transactions','/sales/import','/sales/import-history','/recipes','/recipe-costing','/inventory','/menu','/suppliers','/settings','/settings/units','/settings/categories','/ingredients'].includes(p)).map(([n,p])=><Route key={p} path={p} element={<ComingSoon title={n}/>}/>)}</Routes></main></div>}

function Login(){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[msg,setMsg]=useState('');async function submit(e:React.FormEvent){e.preventDefault();const{error}=await supabase.auth.signInWithPassword({email,password});setMsg(error?.message??'');}return <div className="login"><form onSubmit={submit}><div className="brand dark">INFLOW<span>Café Management</span></div>{!isSupabaseConfigured&&<div className="warn">Configure Supabase environment variables first.</div>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>Sign in</button>{msg&&<p>{msg}</p>}</form></div>}

export default function App(){const[ready,setReady]=useState(false);const[logged,setLogged]=useState(false);useEffect(()=>{void supabase.auth.getSession().then(({data})=>{setLogged(Boolean(data.session));setReady(true)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setLogged(Boolean(s)));return()=>data.subscription.unsubscribe()},[]);if(!ready)return null;return logged?<Shell/>:<Login/>}

function Dashboard(){const[counts,setCounts]=useState({imports:0,sales:0,unmapped:0,costed:0,missing:0});useEffect(()=>{void Promise.all([supabase.from('gpos_imports').select('*',{count:'exact',head:true}),supabase.from('sales_transactions').select('*',{count:'exact',head:true}),supabase.from('sales_items').select('*',{count:'exact',head:true}).eq('mapping_status','UNMAPPED'),supabase.from('sales_items').select('*',{count:'exact',head:true}).eq('costing_status','PROCESSED'),supabase.from('sales_items').select('*',{count:'exact',head:true}).in('costing_status',['MISSING_COST','ERROR'])]).then(([a,b,c,d,e])=>setCounts({imports:a.count??0,sales:b.count??0,unmapped:c.count??0,costed:d.count??0,missing:e.count??0}))},[]);return <><h1>Dashboard</h1><p className="lead">GPOS sales, versioned recipes, inventory ledger and historical COGS foundations are active.</p><div className="cards"><Card t="Committed imports" v={String(counts.imports)}/><Card t="Sales invoices" v={String(counts.sales)}/><Card t="Unmapped sales rows" v={String(counts.unmapped)}/><Card t="Costed sales rows" v={String(counts.costed)}/><Card t="Missing cost / errors" v={String(counts.missing)}/></div></>}
function Card({t,v}:{t:string;v:string}){return <div className="card"><small>{t}</small><strong>{v}</strong></div>}
function ComingSoon({title}:{title:string}){return <><h1>{title}</h1><div className="panel">Coming in the next implementation phase.</div></>}
function Settings(){return <><h1>Settings</h1><div className="panel"><h2>Access and mapping</h2><p>OWNER and MANAGER can manage protected master data, recipes, opening stock and costing. STAFF can import sales under database RLS.</p></div></>}

function MasterData({title,table,fields}:{title:string;table:string;fields:string[]}){const[rows,setRows]=useState<Record<string,unknown>[]>([]);const[form,setForm]=useState<Record<string,string>>({});const[msg,setMsg]=useState('');const load=useCallback(async()=>{const{data,error}=await supabase.from(table).select('*').limit(50);setRows((data??[]) as Record<string,unknown>[]);if(error)setMsg(error.message)},[table]);useEffect(()=>{void load()},[load]);async function create(e:React.FormEvent){e.preventDefault();setMsg('');const payload=Object.fromEntries(fields.map(f=>[f,(f.includes('price')||f.includes('order'))?Number(form[f]||0):(form[f]||null)]));const{error}=await supabase.from(table).insert(payload);if(error){setMsg(error.message);return}setForm({});setMsg('Saved');await load()}async function edit(row:Record<string,unknown>){const payload:Record<string,unknown>={};for(const f of fields){const next=window.prompt(`Update ${f}`,String(row[f]??''));if(next===null)return;payload[f]=(f.includes('price')||f.includes('order'))?Number(next):next||null}const{error}=await supabase.from(table).update(payload).eq('id',String(row.id));if(error)setMsg(error.message);else{setMsg('Updated');await load()}}async function deactivate(id:string){const{error}=await supabase.from(table).update({is_active:false}).eq('id',id);if(error)setMsg(error.message);else await load()}return <><h1>{title}</h1><div className="panel"><form className="crudform" onSubmit={e=>void create(e)}>{fields.map(f=><input key={f} placeholder={f} value={form[f]??''} onChange={e=>setForm(x=>({...x,[f]:e.target.value}))} required={!['name_en','phone','email'].includes(f)}/>) }<button>Add</button></form>{msg&&<p>{msg}</p>}<div className="tablewrap"><table><thead><tr>{fields.map(f=><th key={f}>{f}</th>)}<th>Action</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)}>{fields.map(f=><td key={f}>{String(row[f]??'')}</td>)}<td><button className="smallbtn" onClick={()=>void edit(row)}>Edit</button> {row.is_active!==undefined&&<button className="smallbtn danger" onClick={()=>void deactivate(String(row.id))}>Deactivate</button>}</td></tr>)}</tbody></table></div></div></>}
