create table if not exists public.purchases(
 id uuid primary key default gen_random_uuid(), purchase_no text not null unique, supplier_id uuid references public.suppliers(id), purchase_date date not null default current_date, invoice_reference text, subtotal numeric(14,2) not null default 0 check(subtotal>=0), discount_amount numeric(14,2) not null default 0 check(discount_amount>=0), tax_amount numeric(14,2) not null default 0 check(tax_amount>=0), total_amount numeric(14,2) not null default 0 check(total_amount>=0), payment_status text not null default 'UNPAID', notes text, status text not null default 'DRAFT' check(status in('DRAFT','RECEIVED','CANCELLED')), created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.purchase_items(
 id uuid primary key default gen_random_uuid(), purchase_id uuid not null references public.purchases(id) on delete restrict, ingredient_id uuid not null references public.ingredients(id), purchase_quantity numeric(14,4) not null check(purchase_quantity>0), purchase_unit_id uuid not null references public.units(id), base_quantity numeric(14,4), unit_price numeric(14,4) not null check(unit_price>=0), line_total numeric(14,2) not null check(line_total>=0), cost_per_base_unit numeric(14,4), created_at timestamptz not null default now()
);
create index if not exists purchase_items_purchase_id_idx on public.purchase_items(purchase_id);create index if not exists purchase_items_ingredient_id_idx on public.purchase_items(ingredient_id);create index if not exists purchases_supplier_id_idx on public.purchases(supplier_id);create unique index if not exists inventory_purchase_once_idx on public.inventory_movements(purchase_item_id) where movement_type='PURCHASE' and purchase_item_id is not null;
alter table public.purchases enable row level security;alter table public.purchase_items enable row level security;grant select,insert,update on public.purchases to authenticated;grant select,insert,update on public.purchase_items to authenticated;revoke all on public.purchases,public.purchase_items from anon;
create policy purchases_read on public.purchases for select to authenticated using(private.current_user_role() in('OWNER','MANAGER','STAFF'));
create policy purchases_insert on public.purchases for insert to authenticated with check(created_by=(select auth.uid()) and private.current_user_role() in('OWNER','MANAGER','STAFF'));
create policy purchases_update on public.purchases for update to authenticated using(private.current_user_role() in('OWNER','MANAGER')) with check(private.current_user_role() in('OWNER','MANAGER'));
create policy purchase_items_read on public.purchase_items for select to authenticated using(private.current_user_role() in('OWNER','MANAGER','STAFF'));
create policy purchase_items_insert on public.purchase_items for insert to authenticated with check(private.current_user_role() in('OWNER','MANAGER','STAFF') and exists(select 1 from public.purchases p where p.id=purchase_id and p.status='DRAFT'));
create policy purchase_items_update on public.purchase_items for update to authenticated using(private.current_user_role() in('OWNER','MANAGER') and exists(select 1 from public.purchases p where p.id=purchase_id and p.status='DRAFT')) with check(private.current_user_role() in('OWNER','MANAGER'));
create or replace function public.receive_purchase(p_purchase_id uuid)
returns jsonb language plpgsql security definer set search_path=public,private as $$
declare v_user uuid:=auth.uid();v_role public.user_role;p record;i record;v_base numeric;v_count int:=0;begin
 if v_user is null then raise exception 'Authentication required';end if;select role into v_role from public.profiles where id=v_user and is_active=true;if v_role not in('OWNER','MANAGER') then raise exception 'Owner or manager permission required';end if;
 select * into p from public.purchases where id=p_purchase_id for update;if p.id is null then raise exception 'Purchase not found';end if;if p.status<>'DRAFT' then raise exception 'Only DRAFT purchases can be received';end if;if not exists(select 1 from public.purchase_items where purchase_id=p_purchase_id) then raise exception 'Purchase has no items';end if;
 for i in select * from public.purchase_items where purchase_id=p_purchase_id order by created_at,id loop v_base:=private.to_base_quantity(i.ingredient_id,i.purchase_quantity,i.purchase_unit_id);if v_base<=0 then raise exception 'Invalid base quantity';end if;update public.purchase_items set base_quantity=v_base,cost_per_base_unit=round(i.line_total/v_base,4) where id=i.id;insert into public.inventory_movements(ingredient_id,movement_type,quantity_base_unit,unit_cost,total_cost,reference_type,reference_id,purchase_item_id,occurred_at,notes,created_by) values(i.ingredient_id,'PURCHASE',v_base,round(i.line_total/v_base,4),i.line_total,'PURCHASE',p_purchase_id,i.id,now(),'Purchase received',v_user);v_count:=v_count+1;end loop;
 update public.purchases set status='RECEIVED',subtotal=(select coalesce(sum(line_total),0) from public.purchase_items where purchase_id=p_purchase_id),total_amount=(select coalesce(sum(line_total),0) from public.purchase_items where purchase_id=p_purchase_id)-discount_amount+tax_amount,updated_at=now() where id=p_purchase_id;insert into public.audit_logs(user_id,action,entity_type,entity_id,after_data) values(v_user,'PURCHASE_RECEIVED','purchases',p_purchase_id,jsonb_build_object('items',v_count));return jsonb_build_object('purchase_id',p_purchase_id,'items_received',v_count,'status','RECEIVED');end $$;
revoke all on function public.receive_purchase(uuid) from public,anon;grant execute on function public.receive_purchase(uuid) to authenticated;
