drop policy if exists profiles_read_self_or_management on public.profiles;
create policy profiles_read_self_or_management on public.profiles for select to authenticated using(id=(select auth.uid()) or private.current_user_role() in ('OWNER','MANAGER'));

drop policy if exists units_manage on public.units;
create policy units_insert_management on public.units for insert to authenticated with check(private.current_user_role() in ('OWNER','MANAGER'));
create policy units_update_management on public.units for update to authenticated using(private.current_user_role() in ('OWNER','MANAGER')) with check(private.current_user_role() in ('OWNER','MANAGER'));
drop policy if exists unit_conversions_manage on public.unit_conversions;
create policy unit_conversions_insert_management on public.unit_conversions for insert to authenticated with check(private.current_user_role() in ('OWNER','MANAGER'));
create policy unit_conversions_update_management on public.unit_conversions for update to authenticated using(private.current_user_role() in ('OWNER','MANAGER')) with check(private.current_user_role() in ('OWNER','MANAGER'));
drop policy if exists categories_manage on public.menu_categories;
create policy categories_insert_management on public.menu_categories for insert to authenticated with check(private.current_user_role() in ('OWNER','MANAGER'));
create policy categories_update_management on public.menu_categories for update to authenticated using(private.current_user_role() in ('OWNER','MANAGER')) with check(private.current_user_role() in ('OWNER','MANAGER'));
drop policy if exists menu_items_manage on public.menu_items;
create policy menu_items_insert_management on public.menu_items for insert to authenticated with check(private.current_user_role() in ('OWNER','MANAGER'));
create policy menu_items_update_management on public.menu_items for update to authenticated using(private.current_user_role() in ('OWNER','MANAGER')) with check(private.current_user_role() in ('OWNER','MANAGER'));
drop policy if exists ingredients_manage on public.ingredients;
create policy ingredients_insert_management on public.ingredients for insert to authenticated with check(private.current_user_role() in ('OWNER','MANAGER'));
create policy ingredients_update_management on public.ingredients for update to authenticated using(private.current_user_role() in ('OWNER','MANAGER')) with check(private.current_user_role() in ('OWNER','MANAGER'));
drop policy if exists suppliers_manage on public.suppliers;
create policy suppliers_insert_management on public.suppliers for insert to authenticated with check(private.current_user_role() in ('OWNER','MANAGER'));
create policy suppliers_update_management on public.suppliers for update to authenticated using(private.current_user_role() in ('OWNER','MANAGER')) with check(private.current_user_role() in ('OWNER','MANAGER'));
drop policy if exists recipes_manage on public.recipes;
create policy recipes_insert_management on public.recipes for insert to authenticated with check(private.current_user_role() in ('OWNER','MANAGER'));
create policy recipes_update_management on public.recipes for update to authenticated using(private.current_user_role() in ('OWNER','MANAGER')) with check(private.current_user_role() in ('OWNER','MANAGER'));
drop policy if exists recipe_items_manage on public.recipe_items;
create policy recipe_items_insert_management on public.recipe_items for insert to authenticated with check(private.current_user_role() in ('OWNER','MANAGER'));
create policy recipe_items_update_management on public.recipe_items for update to authenticated using(private.current_user_role() in ('OWNER','MANAGER')) with check(private.current_user_role() in ('OWNER','MANAGER'));
drop policy if exists mapping_manage on public.gpos_product_mapping;
create policy mapping_insert_management on public.gpos_product_mapping for insert to authenticated with check(private.current_user_role() in ('OWNER','MANAGER'));
create policy mapping_update_management on public.gpos_product_mapping for update to authenticated using(private.current_user_role() in ('OWNER','MANAGER')) with check(private.current_user_role() in ('OWNER','MANAGER'));
drop policy if exists payment_mapping_manage on public.payment_channel_mapping;
create policy payment_mapping_insert_management on public.payment_channel_mapping for insert to authenticated with check(private.current_user_role() in ('OWNER','MANAGER'));
create policy payment_mapping_update_management on public.payment_channel_mapping for update to authenticated using(private.current_user_role() in ('OWNER','MANAGER')) with check(private.current_user_role() in ('OWNER','MANAGER'));

drop policy if exists imports_insert on public.gpos_imports;
create policy imports_insert on public.gpos_imports for insert to authenticated with check(imported_by=(select auth.uid()) and private.current_user_role() in ('OWNER','MANAGER','STAFF'));

create index if not exists idx_audit_logs_user on public.audit_logs(user_id);
create index if not exists idx_gpos_imports_imported_by on public.gpos_imports(imported_by);
create index if not exists idx_gpos_mapping_menu_item on public.gpos_product_mapping(menu_item_id);
create index if not exists idx_ingredients_base_unit on public.ingredients(base_unit_id);
create index if not exists idx_ingredients_supplier on public.ingredients(preferred_supplier_id);
create index if not exists idx_menu_items_category on public.menu_items(category_id);
create index if not exists idx_menu_items_default_recipe on public.menu_items(default_recipe_id);
create index if not exists idx_recipes_menu_item on public.recipes(menu_item_id);
create index if not exists idx_recipes_yield_unit on public.recipes(yield_unit_id);
create index if not exists idx_recipe_items_ingredient on public.recipe_items(ingredient_id);
create index if not exists idx_recipe_items_unit on public.recipe_items(unit_id);
create index if not exists idx_sales_items_import on public.sales_items(import_id);
create index if not exists idx_sales_items_transaction on public.sales_items(sales_transaction_id);
create index if not exists idx_sales_items_recipe on public.sales_items(recipe_id);
create index if not exists idx_sales_transactions_import on public.sales_transactions(import_id);
create index if not exists idx_inventory_sales_item on public.inventory_movements(sales_item_id);
